# Set - 1

questions = [
    "What are the fundamental rights guaranteed by the Indian Constitution?",
    "Can the fundamental rights be suspended during an emergency?",
    "What is the procedure for amending the Indian Constitution?",
    "What are the qualifications required to become the President of India?",
    "Explain the concept of parliamentary sovereignty in India.",
    "What is the significance of the Preamble to the Indian Constitution?",
    "How is the President of India elected?",
    "What are the powers and functions of the Supreme Court of India?",
    "Explain the concept of judicial review in the Indian Constitution.",
    "What is the difference between fundamental rights and directive principles of state policy?",
    "What is the composition of the Lok Sabha and the Rajya Sabha?",
    "Can the Indian Constitution be amended to take away the fundamental rights?",
    "Explain the concept of federalism in the Indian Constitution.",
    "What are the qualifications required to become a member of the Rajya Sabha?",
    "What is the procedure for impeachment of the President of India?",
    "Discuss the significance of Article 370 in the Indian Constitution.",
    "What is the role of the Election Commission of India?",
    "Explain the concept of secularism as enshrined in the Indian Constitution.",
    "What are the powers and functions of the Governor of a state in India?",
    "Discuss the role of the Attorney General of India.",
    "Can the President of India dissolve the Lok Sabha?",
    "What is the importance of the Directive Principles of State Policy?",
    "Explain the concept of parliamentary privilege.",
    "What is the procedure for removal of a Governor of a state?",
    "Discuss the concept of equality before law in the Indian Constitution.",
    "What are the grounds for disqualification of a member of Parliament?",
    "Explain the concept of federalism in India with suitable examples.",
    "What is the procedure for appointment of judges to the Supreme Court?",
    "Discuss the role of the Comptroller and Auditor General of India.",
    "What is the significance of the 73rd and 74th Amendments to the Indian Constitution?",
    "Can the Supreme Court review its own judgments?",
    "Discuss the concept of minority rights in the Indian Constitution.",
    "What is the procedure for removal of a judge of the Supreme Court?",
    "Explain the concept of public interest litigation (PIL) in India.",
    "What is the significance of the 42nd Amendment to the Indian Constitution?",
    "Discuss the powers and functions of the Prime Minister of India.",
    "What are the qualifications required to become the Vice President of India?",
    "Explain the concept of parliamentary democracy in India.",
    "What is the procedure for declaration of a financial emergency in India?",
    "Discuss the role of the National Human Rights Commission in India.",
    "What is the procedure for declaration of a national emergency in India?",
    "Explain the concept of reservation in the Indian Constitution.",
    "What are the powers and functions of the Chief Justice of India?",
    "Discuss the significance of the 44th Amendment to the Indian Constitution.",
    "What is the procedure for amendment of the electoral laws in India?",
    "Explain the concept of separation of powers in the Indian Constitution.",
    "What is the procedure for appointment of the Chief Election Commissioner?",
    "Discuss the powers and functions of the State Election Commission.",
    "What is the significance of the 73rd and 74th Amendments to the Indian Constitution?",
    "Explain the concept of judicial activism in India.",
    "What is the procedure for impeachment of a judge of the Supreme Court?",
    "Discuss the role of the Central Vigilance Commission in India.",
    "What is the procedure for appointment of the Attorney General of India?",
    "Explain the concept of parliamentary committees in India.",
    "What is the significance of the 97th Amendment to the Indian Constitution?",
    "Discuss the powers and functions of the Finance Commission.",
    "What is the procedure for removal of the Vice President of India?",
    "Explain the concept of affirmative action in the Indian Constitution.",
    "What are the powers and functions of the Union Public Service Commission?",
    "Discuss the significance of the 86th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief Justice of India?",
    "Explain the concept of judicial independence in India.",
    "What are the powers and functions of the National Commission for Scheduled Castes?",
    "Discuss the role of the Central Bureau of Investigation in India.",
    "What is the procedure for appointment of the Chief Justice of India?",
    "Explain the concept of federal supremacy in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the significance of the 104th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief Election Commissioner?",
    "Explain the concept of concurrent list in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the role of the Special Protection Group in India.",
    "What is the procedure for appointment of the Chief of Army Staff?",
    "Explain the concept of judicial precedent in India.",
    "What are the powers and functions of the National Commission for Backward Classes?",
    "Discuss the significance of the 93rd Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief of Naval Staff?",
    "Explain the concept of judicial restraint in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the role of the National Investigation Agency in India.",
    "What is the procedure for removal of the Chief of Air Staff?",
    "Explain the concept of rule of law in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Safai Karamcharis?",
    "Discuss the significance of the 101st Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Director of the Intelligence Bureau?",
    "Explain the concept of due process of law in India.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the role of the National Security Council in India.",
    "What is the procedure for removal of the Director of the Central Bureau of Investigation?",
    "Explain the concept of judicial activism in India.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the significance of the 126th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chairperson of the National Human Rights Commission?",
    "Explain the concept of judicial review in India.",
    "What are the powers and functions of the National Commission for Scheduled Tribes?",
    "Discuss the role of the National Disaster Management Authority in India.",
    "What is the procedure for removal of the Chairperson of the National Commission for Backward Classes?",
    "Explain the concept of federalism in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the significance of the 108th Amendment to the Indian Constitution.",
    "What rights does the Indian Constitution guarantee as fundamental?",
    "Can fundamental rights be suspended in an emergency?",
    "How can the Indian Constitution be amended?",
    "What qualifications are necessary to be President of India?",
    "Explain parliamentary sovereignty in the context of India.",
    "What is the significance of the Preamble in the Indian Constitution?",
    "What is the process for electing the President of India?",
    "What are the roles and powers of the Supreme Court in India?",
    "Describe the concept of judicial review as outlined in the Indian Constitution.",
    "Distinguish between fundamental rights and directive principles of state policy.",
    "How are the Lok Sabha and Rajya Sabha composed?",
    "Can fundamental rights be removed through constitutional amendments?",
    "Discuss the federalism concept within the Indian Constitution.",
    "What qualifications are required for Rajya Sabha membership?",
    "Explain the impeachment procedure for the President of India.",
    "Analyze the importance of Article 370 in the Indian Constitution.",
    "What is the mandate of the Election Commission of India?",
    "Elaborate on secularism in the Indian Constitutional framework.",
    "Outline the powers and duties of state Governors in India.",
    "Examine the role of the Attorney General of India.",
    "Does the President have the authority to dissolve the Lok Sabha?",
    "Why are Directive Principles of State Policy important?",
    "Elucidate parliamentary privilege in the Indian context.",
    "How can a state Governor be removed from office?",
    "Discuss the principle of equality before law in the Indian Constitution.",
    "What grounds lead to disqualification of Parliament members?",
    "Illustrate federalism in India with examples.",
    "Detail the process for appointing Supreme Court judges.",
    "Explain the role of the Comptroller and Auditor General of India.",
    "What changes did the 73rd and 74th Amendments bring to the Indian Constitution?",
    "Can the Supreme Court review its own decisions?",
    "Discuss minority rights as per the Indian Constitution.",
    "How can a Supreme Court judge be removed?",
    "Describe public interest litigation (PIL) in India.",
    "Analyze the significance of the 42nd Amendment to the Indian Constitution.",
    "Explore the powers and responsibilities of the Prime Minister of India.",
    "What are the eligibility criteria for Vice President of India?",
    "Define parliamentary democracy in the Indian context.",
    "What is the process for declaring a financial emergency in India?",
    "Evaluate the role of the National Human Rights Commission in India.",
    "What steps are involved in declaring a national emergency in India?",
    "Explain the reservation system in the Indian Constitution.",
    "Elaborate on the powers and duties of the Chief Justice of India.",
    "Discuss the significance of the 44th Amendment to the Indian Constitution.",
    "How are electoral laws amended in India?",
    "Examine the concept of separation of powers in the Indian Constitution.",
    "What is the process for appointing the Chief Election Commissioner?",
    "Evaluate the powers and functions of the State Election Commission.",
    "What did the 73rd and 74th Amendments change in the Indian Constitution?",
    "Discuss judicial activism in India.",
    "How can a Supreme Court judge be impeached?",
    "Assess the role of the Central Vigilance Commission in India.",
    "Explain the procedure for appointing the Attorney General of India.",
    "Describe the function of parliamentary committees in India.",
    "Evaluate the significance of the 97th Amendment to the Indian Constitution.",
    "Discuss the powers and functions of the Finance Commission.",
    "How is the Vice President of India removed from office?",
    "Explain affirmative action in the Indian Constitutional framework.",
    "What are the powers and functions of the Union Public Service Commission?",
    "Explore the significance of the 86th Amendment to the Indian Constitution.",
    "What is the process for removing the Chief Justice of India?",
    "Define judicial independence in the Indian context.",
    "Discuss the powers and duties of the National Commission for Scheduled Castes.",
    "Evaluate the role of the Central Bureau of Investigation in India.",
    "How is the Chief Justice of India appointed?",
    "Explain federal supremacy as per the Indian Constitution.",
    "What are the powers and functions of the National Commission for Women?",
    "Assess the significance of the 104th Amendment to the Indian Constitution.",
    "What is the procedure for removing the Chief Election Commissioner?",
    "Explain the concept of the concurrent list in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the role of the Special Protection Group in India.",
    "How is the Chief of Army Staff appointed?",
    "Define judicial precedent in the Indian legal system.",
    "Explore the powers and functions of the National Commission for Backward Classes.",
    "Assess the significance of the 93rd Amendment to the Indian Constitution.",
    "What is the process for removing the Chief of Naval Staff?",
    "Explain judicial restraint in the Indian legal context.",
    "Detail the powers and responsibilities of the National Commission for Protection of Child Rights.",
    "Discuss the role of the National Investigation Agency in India.",
    "How is the Chief of Air Staff removed from office?",
    "Define the rule of law as per the Indian Constitution.",
    "Explain the powers and functions of the National Commission for Safai Karamcharis.",
    "Evaluate the significance of the 101st Amendment to the Indian Constitution.",
    "What is the process for removing the Director of the Intelligence Bureau?",
    "Define due process of law in India.",
    "Detail the powers and functions of the National Commission for Women.",
    "Discuss the role of the National Security Council in India.",
    "How is the Director of the Central Bureau of Investigation removed?",
    "Explain judicial activism in the Indian context.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Assess the significance of the 126th Amendment to the Indian Constitution.",
    "What is the process for removing the Chairperson of the National Human Rights Commission?",
    "Define judicial review in the Indian legal system.",
    "Detail the powers and responsibilities of the National Commission for Scheduled Tribes.",
    "Discuss the role of the National Disaster Management Authority in India.",
    "How is the Chairperson of the National Commission for Backward Classes removed?",
    "Explain federalism in the Indian context.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Assess the significance of the 108th Amendment to the Indian Constitution.",
     "What basic rights does the Indian Constitution promise?",
    "Can the main rights be stopped during an emergency?",
    "How can the Indian Constitution be changed?",
    "What do you need to become India's President?",
    "What does parliamentary sovereignty mean in India?",
    "Why is the Preamble important in India's Constitution?",
    "How is the President of India chosen?",
    "What does the Supreme Court do in India?",
    "How does the court check if laws are fair in India?",
    "What's the difference between main rights and state guidelines in India?",
    "Who makes up the Lok Sabha and Rajya Sabha?",
    "Can the main rights be removed by changing the Constitution?",
    "What's federalism, and why is it in India's Constitution?",
    "What do you need to be in the Rajya Sabha?",
    "How can the President be removed from office?",
    "Why is Article 370 important?",
    "What's the Election Commission's job?",
    "What's secularism, and why is it in India's Constitution?",
    "What does a state Governor do?",
    "What's the Attorney General's role?",
    "Can the President end the Lok Sabha?",
    "Why are State Policy Guidelines important?",
    "What's parliamentary privilege?",
    "How can a Governor be removed?",
    "What's equality before the law mean?",
    "Why would a member of Parliament lose their job?",
    "How does India balance power between central and state governments?",
    "How are Supreme Court judges chosen?",
    "What does the Comptroller and Auditor General do?",
    "How did the 73rd and 74th Amendments change things?",
    "Can the Supreme Court change its mind?",
    "How does India protect minority rights?",
    "How can a Supreme Court judge be fired?",
    "What's public interest litigation?",
    "Why was the 42nd Amendment important?",
    "What does the Prime Minister do?",
    "What do you need to be Vice President?",
    "What's a parliamentary democracy?",
    "How do you declare a financial emergency?",
    "What does the National Human Rights Commission do?",
    "How do you declare a national emergency?",
    "What's reservation, and why is it in India's Constitution?",
    "What does the Chief Justice of India do?",
    "Why did the 44th Amendment matter?",
    "How do you change election laws?",
    "Why are powers separated in the Indian Constitution?",
    "How is the Chief Election Commissioner chosen?",
    "What do State Election Commissions do?",
    "Why did the 73rd and 74th Amendments matter?",
    "What's judicial activism?",
    "How can a Supreme Court judge be fired?",
    "What does the Central Vigilance Commission do?",
    "How is the Attorney General chosen?",
    "What do parliamentary committees do?",
    "Why was the 97th Amendment important?",
    "What do Finance Commissions do?",
    "How is the Vice President removed?",
    "What's affirmative action?",
    "What does the Union Public Service Commission do?",
    "Why was the 86th Amendment important?",
    "How is the Chief Justice removed?",
    "What's judicial independence?",
    "What does the National Commission for Scheduled Castes do?",
    "What does the CBI do?",
    "How is the Chief Justice chosen?",
    "What's federal supremacy?",
    "What does the National Commission for Women do?",
    "Why was the 104th Amendment important?",
    "How is the Chief Election Commissioner removed?",
    "What's the concurrent list?",
    "What does the National Commission for Minorities do?",
    "What does the Special Protection Group do?",
    "How is the Chief of Army Staff chosen?",
    "What's judicial precedent?",
    "What does the National Commission for Backward Classes do?",
    "Why was the 93rd Amendment important?",
    "How is the Chief of Naval Staff removed?",
    "What's judicial restraint?",
    "What does the National Commission for Protection of Child Rights do?",
    "What does the NIA do?",
    "How is the Chief of Air Staff removed?",
    "What's the rule of law?",
    "What does the National Commission for Safai Karamcharis do?",
    "Why was the 101st Amendment important?",
    "How is the Director of the Intelligence Bureau removed?",
    "What's due process of law?",
    "What does the National Commission for Women do?",
    "What does the National Security Council do?",
    "How is the Director of the CBI removed?",
    "What's judicial activism?",
    "What does the National Commission for Minorities do?",
    "Why was the 126th Amendment important?",
    "How is the Chairperson of the NHRC removed?",
    "What's judicial review?",
    "What does the National Commission for Scheduled Tribes do?",
    "What does the NDMA do?",
    "How is the Chairperson of the NCBC removed?",
    "What's federalism?",
    "What does the National Commission for Protection of Child Rights do?",
    "Why was the 108th Amendment important?"
]

