questions = [
    "What is the legal definition of cybercrime according to the Indian Constitution?",
    "Can you explain the penalties for hacking under Indian cyber law?",
    "How does the Indian Constitution protect against online identity theft?",
    "What are the legal implications of spreading fake news online in India?",
    "How does the Indian legal system address cyberbullying?",
    "Can you explain the role of the Information Technology Act in combating cybercrimes?",
    "What are the legal consequences of unauthorized access to computer systems in India?",
    "How does Indian law regulate online financial fraud?",
    "Can you explain the jurisdictional issues in prosecuting cybercrimes in India?",
    "What are the legal protections for individuals' privacy online according to Indian law?",
    "How does the Indian Constitution address cyber terrorism?",
    "Can you explain the process of reporting cybercrimes to the authorities in India?",
    "What are the legal remedies available to victims of online harassment in India?",
    "How does Indian law regulate online gambling and betting?",
    "Can you explain the role of intermediaries in Indian cyber law?",
    "What are the legal requirements for data protection and privacy in India?",
    "How does the Indian Constitution address online hate speech and incitement to violence?",
    "Can you explain the legal framework for electronic signatures and digital documents in India?",
    "What are the legal consequences of copyright infringement online in India?",
    "How does Indian law address revenge porn and non-consensual dissemination of intimate images?",
    "Can you explain the legal provisions for child protection online in India?",
    "What are the regulations regarding cybersecurity practices for businesses in India?",
    "How does the Indian legal system handle cases of online stalking?",
    "Can you explain the concept of net neutrality in the context of Indian cyber law?",
    "What are the legal obligations of internet service providers (ISPs) in India?",
    "How does the Indian Constitution protect against online fraud and phishing scams?",
    "Can you explain the role of the Cyber Appellate Tribunal in India?",
    "What are the legal implications of data breaches under Indian law?",
    "How does Indian law address online defamation and libel?",
    "What are the legal requirements for reporting data breaches in India?",
    "Can you explain the process of obtaining a warrant for electronic surveillance in India?",
    "How does the Indian legal system handle cases of online extortion?",
    "What are the legal protections for whistleblowers who expose cybercrimes in India?",
    "Can you explain the concept of digital sovereignty in the context of Indian cyber law?",
    "How does Indian law address the use of encryption technology?",
    "What are the legal consequences of cyber espionage in India?",
    "Can you explain the role of international cooperation in combating cybercrimes in India?",
    "How does the Indian Constitution protect against online censorship and surveillance?",
    "What are the legal requirements for data localization in India?",
    "Can you explain the legal framework for cloud computing in India?",
    "How does Indian law address the issue of cyber warfare?",
    "What are the legal protections for journalists and freedom of speech online in India?",
    "Can you explain the legal provisions for electronic evidence in Indian courts?",
    "How does the Indian legal system handle cases of online fraud targeting senior citizens?",
    "What are the legal implications of doxxing under Indian cyber law?",
    "Can you explain the role of the National Cyber Security Coordinator in India?",
    "How does Indian law address the unauthorized interception of electronic communications?",
    "What are the legal requirements for cybersecurity audits in India?",
    "Can you explain the legal provisions for incident response and cyber crisis management in India?",
    "How does the Indian Constitution protect against online harassment based on gender or sexuality?",
    "What are the legal consequences of tampering with electronic records in India?",
    "Can you explain the process of digital forensics in Indian cyber investigations?",
    "How does Indian law address the issue of online radicalization and extremism?",
    "What are the legal protections for intellectual property rights online in India?",
    "Can you explain the legal framework for regulating social media platforms in India?",
    "How does the Indian legal system handle cases of online piracy and counterfeiting?",
    "What are the legal obligations of businesses regarding data breach notifications in India?",
    "Can you explain the legal provisions for electronic payments and digital currencies in India?",
    "How does Indian law address the issue of online scamming and fraudulent schemes?",
    "What are the legal protections for victims of online financial fraud in India?",
    "Can you explain the process of obtaining a restraining order against online harassment in India?",
    "How does the Indian Constitution protect against online discrimination and hate speech?",
    "What are the legal requirements for conducting penetration testing and vulnerability assessments in India?",
    "Can you explain the role of the Computer Emergency Response Team (CERT-In) in India?",
    "How does Indian law address the issue of online cyberbullying in schools and colleges?",
    "What are the legal consequences of spreading misinformation and fake news online in India?",
    "Can you explain the legal provisions for the regulation of online marketplaces and e-commerce platforms in India?",
    "How does the Indian legal system handle cases of online identity theft and impersonation?",
    "What are the legal protections for whistleblowers who report cybercrimes in India?",
    "Can you explain the role of the judiciary in interpreting and enforcing Indian cyber laws?",
    "How does Indian law address the issue of online harassment in the workplace?",
    "What are the legal requirements for conducting background checks on employees in India?",
    "Can you explain the legal provisions for the protection of critical infrastructure from cyber threats in India?",
    "How does the Indian Constitution protect against online surveillance and privacy violations by the government?",
    "What are the legal implications of cyberbullying on minors under Indian law?",
    "Can you explain the process of reporting cyber threats and vulnerabilities to the authorities in India?",
    "How does Indian law address the issue of online grooming and child exploitation?",
    "What are the legal protections for individuals' right to encryption and secure communication in India?",
    "Can you explain the role of the National Cyber Crime Reporting Portal in India?",
    "How does the Indian legal system handle cases of online defamation and reputation damage?",
    "What are the legal consequences of unauthorized access to computer networks and systems in India?",
    "Can you explain the legal provisions for the preservation and admissibility of electronic evidence in Indian courts?",
    "How does Indian law address the issue of online harassment in online gaming communities?",
    "What are the legal protections for victims of cyberstalking and online harassment in India?",
    "Can you explain the role of cybersecurity awareness and education programs in India?",
    "How does the Indian Constitution protect against online surveillance and interception of communications?",
    "What are the legal requirements for the use of biometric data and facial recognition technology in India?",
    "Can you explain the legal provisions for the regulation of online content and social media platforms in India?",
    "How does Indian law address the issue of online impersonation and fraud?",
    "What are the legal protections for individuals' right to anonymity and pseudonymity online in India?",
    "Can you explain the role of international treaties and agreements in shaping Indian cyber law?",
    "How does the Indian legal system handle cases of online harassment and cyberbullying in universities?",
    "What are the legal consequences of online harassment and stalking under Indian law?",
    "Can you explain the legal provisions for the protection of minors from online predators in India?",
    "How does Indian law address the issue of online radicalization and recruitment by terrorist groups?",
    "What are the legal protections for individuals' right to privacy and data protection in India?",
    "Can you explain the process of obtaining a court order for the interception of electronic communications in India?",
    "How does the Indian Constitution protect against online censorship and content regulation?",
    "What are the legal requirements for the storage and retention of electronic records in India?",
    "Can you explain the role of digital forensics in investigating and prosecuting cybercrimes in India?"
]
