questions = [
    "What are the fundamental rights guaranteed by the Indian Constitution?",
    "Can the fundamental rights be suspended during an emergency?",
    "What is the procedure for amending the Indian Constitution?",
    "What are the qualifications required to become the President of India?",
    "Explain the concept of parliamentary sovereignty in India.",
    "What is the significance of the Preamble to the Indian Constitution?",
    "How is the President of India elected?",
    "What are the powers and functions of the Supreme Court of India?",
    "Explain the concept of judicial review in the Indian Constitution.",
    "What is the difference between fundamental rights and directive principles of state policy?",
    "What is the composition of the Lok Sabha and the Rajya Sabha?",
    "Can the Indian Constitution be amended to take away the fundamental rights?",
    "Explain the concept of federalism in the Indian Constitution.",
    "What are the qualifications required to become a member of the Rajya Sabha?",
    "What is the procedure for impeachment of the President of India?",
    "Discuss the significance of Article 370 in the Indian Constitution.",
    "What is the role of the Election Commission of India?",
    "Explain the concept of secularism as enshrined in the Indian Constitution.",
    "What are the powers and functions of the Governor of a state in India?",
    "Discuss the role of the Attorney General of India.",
    "Can the President of India dissolve the Lok Sabha?",
    "What is the importance of the Directive Principles of State Policy?",
    "Explain the concept of parliamentary privilege.",
    "What is the procedure for removal of a Governor of a state?",
    "Discuss the concept of equality before law in the Indian Constitution.",
    "What are the grounds for disqualification of a member of Parliament?",
    "Explain the concept of federalism in India with suitable examples.",
    "What is the procedure for appointment of judges to the Supreme Court?",
    "Discuss the role of the Comptroller and Auditor General of India.",
    "What is the significance of the 73rd and 74th Amendments to the Indian Constitution?",
    "Can the Supreme Court review its own judgments?",
    "Discuss the concept of minority rights in the Indian Constitution.",
    "What is the procedure for removal of a judge of the Supreme Court?",
    "Explain the concept of public interest litigation (PIL) in India.",
    "What is the significance of the 42nd Amendment to the Indian Constitution?",
    "Discuss the powers and functions of the Prime Minister of India.",
    "What are the qualifications required to become the Vice President of India?",
    "Explain the concept of parliamentary democracy in India.",
    "What is the procedure for declaration of a financial emergency in India?",
    "Discuss the role of the National Human Rights Commission in India.",
    "What is the procedure for declaration of a national emergency in India?",
    "Explain the concept of reservation in the Indian Constitution.",
    "What are the powers and functions of the Chief Justice of India?",
    "Discuss the significance of the 44th Amendment to the Indian Constitution.",
    "What is the procedure for amendment of the electoral laws in India?",
    "Explain the concept of separation of powers in the Indian Constitution.",
    "What is the procedure for appointment of the Chief Election Commissioner?",
    "Discuss the powers and functions of the State Election Commission.",
    "What is the significance of the 73rd and 74th Amendments to the Indian Constitution?",
    "Explain the concept of judicial activism in India.",
    "What is the procedure for impeachment of a judge of the Supreme Court?",
    "Discuss the role of the Central Vigilance Commission in India.",
    "What is the procedure for appointment of the Attorney General of India?",
    "Explain the concept of parliamentary committees in India.",
    "What is the significance of the 97th Amendment to the Indian Constitution?",
    "Discuss the powers and functions of the Finance Commission.",
    "What is the procedure for removal of the Vice President of India?",
    "Explain the concept of affirmative action in the Indian Constitution.",
    "What are the powers and functions of the Union Public Service Commission?",
    "Discuss the significance of the 86th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief Justice of India?",
    "Explain the concept of judicial independence in India.",
    "What are the powers and functions of the National Commission for Scheduled Castes?",
    "Discuss the role of the Central Bureau of Investigation in India.",
    "What is the procedure for appointment of the Chief Justice of India?",
    "Explain the concept of federal supremacy in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the significance of the 104th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief Election Commissioner?",
    "Explain the concept of concurrent list in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the role of the Special Protection Group in India.",
    "What is the procedure for appointment of the Chief of Army Staff?",
    "Explain the concept of judicial precedent in India.",
    "What are the powers and functions of the National Commission for Backward Classes?",
    "Discuss the significance of the 93rd Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief of Naval Staff?",
    "Explain the concept of judicial restraint in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the role of the National Investigation Agency in India.",
    "What is the procedure for removal of the Chief of Air Staff?",
    "Explain the concept of rule of law in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Safai Karamcharis?",
    "Discuss the significance of the 101st Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Director of the Intelligence Bureau?",
    "Explain the concept of due process of law in India.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the role of the National Security Council in India.",
    "What is the procedure for removal of the Director of the Central Bureau of Investigation?",
    "Explain the concept of judicial activism in India.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the significance of the 126th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chairperson of the National Human Rights Commission?",
    "Explain the concept of judicial review in India.",
    "What are the powers and functions of the National Commission for Scheduled Tribes?",
    "Discuss the role of the National Disaster Management Authority in India.",
    "What is the procedure for removal of the Chairperson of the National Commission for Backward Classes?",
    "Explain the concept of federalism in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the significance of the 108th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chairperson of the National Commission for Safai Karamcharis?",
    "Explain the concept of judicial activism in India.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the significance of the 126th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chief Justice of India?",
    "Explain the concept of judicial review in India.",
    "What are the powers and functions of the National Commission for Scheduled Tribes?",
    "Discuss the role of the National Disaster Management Authority in India.",
    "What is the procedure for removal of the Chairperson of the National Commission for Backward Classes?",
    "Explain the concept of federalism in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the significance of the 108th Amendment to the Indian Constitution.",
    "What is the procedure for removal of the Chairperson of the National Commission for Safai Karamcharis?",
     "What does the Basic Structure Doctrine signify within Indian constitutional law?",
    "Elaborate on the roles and responsibilities of the Prime Minister's Office in India.",
    "Is it within the President of India's authority to remove a Governor of a state?",
    "Explain the concept of double jeopardy as applied in the Indian legal framework.",
    "Describe the functions and powers of the Union Cabinet in India.",
    "Highlight the significance of the 52nd Amendment to the Indian Constitution.",
    "Can the Supreme Court of India assess the validity of a constitutional amendment?",
    "Discuss the notion of judicial overreach in the context of Indian jurisprudence.",
    "How is the Chief Justice of a High Court appointed?",
    "Enumerate the duties of the Solicitor General of India.",
    "What is the process for implementing President's Rule in a state?",
    "Define due process within the Indian legal system.",
    "What are the responsibilities of the Central Information Commission?",
    "Does the President of India have the authority to veto legislation passed by Parliament?",
    "What was the significance of the 105th Amendment to the Indian Constitution?",
    "How can a member of a state legislative assembly be removed from office?",
    "Define the principle of equality of opportunity in the Indian Constitution.",
    "Enumerate the functions and powers of the Central Bureau of Investigation.",
    "Is it possible for the Prime Minister of India to serve as a Rajya Sabha member?",
    "Explain the importance of the 79th Amendment to the Indian Constitution.",
    "What is the protocol for declaring a state emergency in India?",
    "Describe the mechanism of constructive vote of no confidence in the Indian Parliament.",
    "What are the duties of the National Commission for Women?",
    "Can the Supreme Court initiate contempt proceedings independently?",
    "Evaluate the significance of the 108th Amendment to the Indian Constitution.",
    "How can a member of a legislative council be dismissed?",
    "Explain the concept of absolute majority as applicable in the Indian Parliament.",
    "What are the tasks entrusted to the Central Board of Film Certification?",
    "Does the President of India possess the authority to dissolve the Rajya Sabha?",
    "Analyze the importance of the 86th Amendment to the Indian Constitution.",
    "What are the steps for removing a member of a legislative assembly?",
    "Define statutory interpretation within Indian legal practice.",
    "What are the responsibilities of the National Human Rights Commission?",
    "Can the Vice President preside over the Rajya Sabha without being a member?",
    "Assess the significance of the 123rd Amendment to the Indian Constitution.",
    "How can a member of a municipal corporation be removed from office?",
    "Define public interest litigation within the Indian legal system.",
    "What are the duties of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Discuss the importance of the 96th Amendment to the Indian Constitution.",
    "What is the procedure for ousting a member of a municipal council?",
    "Explain the concept of judicial activism as seen in Indian courts.",
    "What are the tasks delegated to the National Commission for Scheduled Tribes?",
    "Can the President of India decline a mercy petition?",
    "Analyze the significance of the 100th Amendment to the Indian Constitution.",
    "How can a member of a legislative assembly be dismissed?",
    "Define the rule of law within the Indian Constitution.",
    "Enumerate the responsibilities of the National Commission for Protection of Child Rights.",
    "Can the Vice President of India cast a decisive vote in the Rajya Sabha?",
    "Discuss the significance of the 124th Amendment to the Indian Constitution.",
    "What is the procedure for ousting a member of a legislative council?",
    "Explain the concept of judicial restraint within Indian courts.",
    "What are the duties of the National Commission for Minorities?",
    "Is the Speaker of the Lok Sabha subject to removal by a simple majority?",
    "Analyze the significance of the 126th Amendment to the Indian Constitution.",
    "How can a member of a municipal corporation be removed from office?",
    "Define judicial review within the Indian legal system.",
    "What are the tasks assigned to the National Commission for Backward Classes?",
    "Does the Prime Minister of India possess the authority to dissolve the Lok Sabha?",
    "Discuss the importance of the 128th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a panchayat?",
    "Explain the concept of separation of powers within the Indian Constitution.",
    "What are the responsibilities of the National Commission for Women?",
    "Can the President of India dissolve the Rajya Sabha?",
    "Assess the significance of the 130th Amendment to the Indian Constitution.",
    "How can a member of a municipal council be removed from office?",
    "Define federalism as it pertains to India.",
    "What are the duties of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Discuss the importance of the 132nd Amendment to the Indian Constitution.",
    "What is the procedure for removing a member of a gram panchayat?",
    "Explain the concept of judicial activism in India.",
    "What are the tasks assigned to the National Commission for Scheduled Tribes?",
    "Can the President of India reject a mercy petition?",
    "Analyze the significance of the 134th Amendment to the Indian Constitution.",
    "How can a member of a legislative assembly be removed from office?",
    "Define the rule of law within the Indian Constitution.",
    "Enumerate the responsibilities of the National Commission for Protection of Child Rights.",
    "Can the Vice President of India cast a decisive vote in the Rajya Sabha?",
    "Discuss the importance of the 136th Amendment to the Indian Constitution.",
    "What is the procedure for ousting a member of a legislative council?",
    "Explain the concept of judicial restraint within Indian courts.",
    "What are the duties of the National Commission for Minorities?",
    "Is the Speaker of the Lok Sabha subject to removal by a simple majority?",
    "Analyze the significance of the 138th Amendment to the Indian Constitution.",
    "How can a member of a municipal corporation be removed from office?",
    "Define judicial review within the Indian legal system.",
    "What are the tasks assigned to the National Commission for Backward Classes?",
    "Does the Prime Minister of India possess the authority to dissolve the Lok Sabha?",
    "Discuss the importance of the 140th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a panchayat?",
    "Explain the concept of separation of powers within the Indian Constitution.",
    "What are the responsibilities of the National Commission for Women?",
    "Can the President of India dissolve the Rajya Sabha?",
    "Assess the significance of the 142nd Amendment to the Indian Constitution.",
    "How can a member of a municipal council be removed from office?",
    "Define federalism as it pertains to India.",
    "What are the duties of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Discuss the importance of the 144th Amendment to the Indian Constitution.",
      "What is the importance of the Basic Structure Doctrine in Indian constitutional law?",
    "Elaborate on the roles and responsibilities of the Prime Minister's Office in India.",
    "Is it within the President of India's authority to dismiss a state Governor?",
    "Clarify the concept of double jeopardy as it applies in the Indian legal framework.",
    "Describe the functions and powers vested in the Union Cabinet of India.",
    "How did the 52nd Amendment impact the Indian Constitution?",
    "Can the Supreme Court of India assess the validity of a constitutional amendment?",
    "Define judicial overreach within the context of India's legal system.",
    "How is a Chief Justice of a High Court appointed?",
    "Explain the role played by the Solicitor General of India.",
    "Under what circumstances can President's Rule be imposed in a state, and what is the procedure?",
    "Define due process as it pertains to Indian law.",
    "What are the duties and authority of the Central Information Commission?",
    "Does the President of India possess the authority to veto a bill passed by Parliament?",
    "How did the 105th Amendment alter the Indian Constitution?",
    "What is the process for ousting a member of a state legislative assembly?",
    "Explain the principle of equality of opportunity enshrined in the Indian Constitution.",
    "What are the functions and powers of the Central Bureau of Investigation?",
    "Can the Prime Minister of India concurrently serve as a member of the Rajya Sabha?",
    "In what manner did the 79th Amendment impact the Indian Constitution?",
    "How is a state emergency declared in India?",
    "Define the concept of constructive vote of no confidence within the Indian Parliament.",
    "Enumerate the responsibilities and authority of the National Commission for Women.",
    "Can the Supreme Court of India initiate contempt proceedings on its own volition?",
    "How did the 108th Amendment modify the Indian Constitution?",
    "What is the process for removing a member of a legislative council?",
    "Explain the notion of absolute majority within the Indian Parliament.",
    "What are the roles and responsibilities of the Central Board of Film Certification?",
    "Does the President of India possess the power to dissolve the Rajya Sabha?",
    "What alterations were introduced by the 86th Amendment to the Indian Constitution?",
    "How does one go about removing a member of a municipal corporation?",
    "Define statutory interpretation as practiced in Indian courts.",
    "What are the duties and authority of the National Human Rights Commission?",
    "Can the Vice President of India preside over the Rajya Sabha without being a member?",
    "Explain the implications of the 123rd Amendment to the Indian Constitution.",
    "What is the process for ousting a member of a legislative assembly?",
    "Define public interest litigation within the Indian legal system.",
    "What are the duties and authority of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Elaborate on the effects of the 96th Amendment on the Indian Constitution.",
    "How does one go about removing a member of a municipal council?",
    "Define judicial activism as observed in India.",
    "What are the duties and authority of the National Commission for Scheduled Tribes?",
    "Can the President of India reject a mercy petition?",
    "Explain the implications of the 100th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a legislative assembly?",
    "Define the concept of rule of law within the Indian Constitution.",
    "What are the duties and authority of the National Commission for Protection of Child Rights?",
    "Can the Vice President of India cast a deciding vote in the Rajya Sabha?",
    "Elaborate on the effects of the 124th Amendment on the Indian Constitution.",
    "How does one go about removing a member of a legislative council?",
    "Define judicial restraint as practiced in Indian courts.",
    "What are the duties and authority of the National Commission for Minorities?",
    "Can the Speaker of Lok Sabha be removed by a simple majority?",
    "Explain the implications of the 126th Amendment to the Indian Constitution.",
    "What is the process for ousting a member of a municipal corporation?",
    "Define judicial review within the Indian legal system.",
    "What are the duties and authority of the National Commission for Backward Classes?",
    "Does the Prime Minister of India have the authority to dissolve the Lok Sabha?",
    "Elaborate on the effects of the 128th Amendment on the Indian Constitution.",
    "How does one go about removing a member of a panchayat?",
    "Define the concept of separation of powers within the Indian Constitution.",
    "What are the duties and authority of the National Commission for Women?",
    "Can the President of India dissolve the Rajya Sabha?",
    "Explain the implications of the 130th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a municipal council?",
    "Define federalism as practiced in India.",
    "What are the duties and authority of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Elaborate on the effects of the 132nd Amendment on the Indian Constitution.",
    "How does one go about removing a member of a gram panchayat?",
    "Define judicial activism as observed in India.",
    "What are the duties and authority of the National Commission for Scheduled Tribes?",
    "Can the President of India reject a mercy petition?",
    "Explain the implications of the 134th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a legislative assembly?",
    "Define the concept of rule of law within the Indian Constitution.",
    "What are the duties and authority of the National Commission for Protection of Child Rights?",
    "Can the Vice President of India cast a deciding vote in the Rajya Sabha?",
    "Elaborate on the effects of the 136th Amendment on the Indian Constitution.",
    "How does one go about removing a member of a legislative council?",
    "Define judicial restraint as practiced in Indian courts.",
    "What are the duties and authority of the National Commission for Minorities?",
    "Can the Speaker of Lok Sabha be removed by a simple majority?",
    "Explain the implications of the 138th Amendment to the Indian Constitution.",
    "What is the process for removing a member of a municipal corporation?",
    "Define judicial review within the Indian legal system.",
    "What are the duties and authority of the National Commission for Backward Classes?",
    "Does the Prime Minister of India have the authority to dissolve the Lok Sabha?",
    "Elaborate on the effects of the 140th Amendment on the Indian Constitution.",
    "How does one go about removing a member of a panchayat?",
    "Define the concept of separation of powers within the Indian Constitution.",
    "What are the duties and authority of the National Commission for Women?",
    "Can the President of India dissolve the Rajya Sabha?",
    "Explain the implications of the 142nd Amendment to the Indian Constitution.",
    "What is the process for removing a member of a municipal council?",
    "Define federalism as practiced in India.",
    "What are the duties and authority of the National Commission for Safai Karamcharis?",
    "Is it permissible for the Attorney General of India to hold a parliamentary position?",
    "Elaborate on the effects of the 144th Amendment on the Indian Constitution."
]

