questions = [
    "What are the penalties for driving without a valid license in India?",
    "Can I use my international driving license to drive in India?",
    "What is the legal blood alcohol limit for driving in India?",
    "How can I contest a traffic ticket in India?",
    "What are the rules regarding seatbelt usage in India?",
    "Is it legal to use a mobile phone while driving in India?",
    "What are the penalties for speeding in India?",
    "Can I contest a red light camera ticket in India?",
    "Are there any specific rules for helmet usage while riding a two-wheeler?",
    "What should I do if I'm involved in a hit-and-run accident in India?",
    "Are there any specific rules for child car seats in India?",
    "How can I renew my vehicle registration in India?",
    "What are the consequences of driving without insurance in India?",
    "Are there any specific rules for transporting goods in a vehicle in India?",
    "What are the regulations for using horns in India?",
    "Can I drive a car with tinted windows in India?",
    "What should I do if I witness a road accident in India?",
    "How can I report a reckless driver in India?",
    "Are there any specific rules for parking on public roads in India?",
    "What are the penalties for driving without wearing glasses/contact lenses if prescribed?",
    "Can I drive a commercial vehicle with a regular driver's license in India?",
    "What are the rules regarding overtaking on highways in India?",
    "Is it legal to modify my vehicle's exhaust system in India?",
    "What are the regulations for driving near schools and hospitals in India?",
    "Can I be fined for littering from my vehicle in India?",
    "How can I obtain a learner's license in India?",
    "Are there any restrictions on vehicle modifications in India?",
    "What should I do if my vehicle breaks down on the highway in India?",
    "Can I drive a vehicle with a cracked windshield in India?",
    "What are the rules regarding using high beam headlights in India?",
    "Are there any specific rules for cyclists on Indian roads?",
    "What should I do if I hit a domestic animal while driving in India?",
    "Can I contest a traffic fine issued by a traffic police officer in India?",
    "Are there any regulations for transporting pets in a vehicle in India?",
    "What are the penalties for driving without valid emission certification in India?",
    "How can I obtain a duplicate vehicle registration certificate in India?",
    "Can I use a dashcam in my vehicle in India?",
    "What are the rules for driving in adverse weather conditions in India?",
    "How can I check my vehicle's challan status online in India?",
    "Are there any specific rules for driving in hilly areas in India?",
    "Can I drive a vehicle with expired insurance if I haven't renewed it yet?",
    "What should I do if I witness a road rage incident in India?",
    "Are there any specific rules for using roundabouts in India?",
    "Can I contest a parking ticket issued by a private parking lot in India?",
    "What are the penalties for driving without a pollution control certificate in India?",
    "How can I obtain a disabled parking permit in India?",
    "Are there any regulations for using GPS devices while driving in India?",
    "What are the penalties for driving without a valid fitness certificate in India?",
    "Can I transport hazardous materials in my vehicle in India?",
    "What should I do if I receive a fake traffic fine notice in India?",
    "Are there any specific rules for driving near railway crossings in India?",
    "Can I drive a vehicle with expired registration if I'm in the process of renewing it?",
    "What are the regulations for using bicycle lanes in India?",
    "How can I check if my vehicle has any pending traffic fines in India?",
    "Can I drive a vehicle with a cracked taillight in India?",
    "What should I do if I'm involved in a minor fender bender in India?",
    "Are there any specific rules for driving in residential areas in India?",
    "Can I contest a traffic fine issued by an automated traffic camera in India?",
    "What are the penalties for driving without a valid pollution under control (PUC) certificate?",
    "How can I obtain a commercial driver's license (CDL) in India?",
    "Are there any specific rules for using headlights during the daytime in India?",
    "Can I tow another vehicle with my car in India?",
    "What are the regulations for using bicycle helmets in India?",
    "How can I apply for a vehicle loan in India?",
    "Can I drive a vehicle with expired temporary registration in India?",
    "What should I do if I accidentally hit a pedestrian in India?",
    "Are there any specific rules for using U-turns in India?",
    "Can I contest a traffic fine issued by a traffic warden in India?",
    "What are the penalties for driving without carrying vehicle documents in India?",
    "How can I obtain a no objection certificate (NOC) for my vehicle in India?",
    "Are there any specific rules for driving near construction zones in India?",
    "Can I drive a vehicle with a cracked side mirror in India?",
    "What should I do if my vehicle is towed away for illegal parking in India?",
    "Are there any regulations for using electric scooters on Indian roads?",
    "How can I obtain a transport permit for my commercial vehicle in India?",
    "Can I contest a traffic fine issued in another state of India?",
    "What are the penalties for driving without wearing a seatbelt in India?",
    "How can I register a complaint against a reckless driver in India?",
    "Are there any specific rules for using hazard lights while driving in India?",
    "Can I drive a vehicle with a broken speedometer in India?",
    "What should I do if my vehicle is stolen in India?",
    "Are there any regulations for using carpool lanes in India?",
    "How can I obtain a vehicle's accident history report in India?",
    "Can I contest a traffic fine issued due to a malfunctioning traffic signal in India?",
    "What are the penalties for driving without carrying a first aid kit in India?",
    "How can I obtain a commercial vehicle permit in India?",
    "Are there any specific rules for driving near wildlife reserves in India?",
    "Can I drive a vehicle with expired temporary registration plates in India?",
    "What should I do if I witness a road accident involving multiple vehicles in India?",
    "Are there any regulations for using electric bicycles on Indian roads?",
    "How can I obtain a copy of my driving record in India?",
    "Can I contest a traffic fine issued based on eyewitness testimony in India?",
    "What are the penalties for driving without wearing a helmet on a two-wheeler in India?",
    "How can I obtain a vehicle's ownership history report in India?",
    "Are there any specific rules for driving near schools during school hours in India?",
    "Can I drive a vehicle with expired insurance if I'm not using it?",
    "What should I do if I accidentally damage public property while driving in India?",
    "Are there any regulations for using hands-free devices while driving in India?",
    "How can I obtain a commercial vehicle insurance policy in India?",
    "Can I contest a traffic fine issued for parking in a no-parking zone if signage was unclear?"
]
