questions = [
    "What are the fundamental duties prescribed by the Indian Constitution?",
    "Explain the concept of judicial activism in the context of Indian judiciary.",
    "What is the significance of the Basic Structure Doctrine in Indian constitutional law?",
    "Discuss the powers and functions of the State Legislative Assembly.",
    "Can a citizen of India be deprived of citizenship? If yes, under what circumstances?",
    "Explain the procedure for the appointment and removal of the Chief Justice of a High Court.",
    "What are the grounds for disqualification of a member of a State Legislative Assembly?",
    "Discuss the role of the Finance Commission in India.",
    "Can a citizen of India directly approach the Supreme Court for enforcement of fundamental rights?",
    "Explain the concept of cooperative federalism as envisaged in the Indian Constitution.",
    "What are the powers and functions of the State Public Service Commission?",
    "Discuss the provisions regarding the establishment and jurisdiction of High Courts in India.",
    "What is the procedure for the imposition of President's Rule in a state?",
    "Explain the procedure for the impeachment of the Vice President of India.",
    "What are the provisions for reservation of seats for Scheduled Castes and Scheduled Tribes in the Lok Sabha?",
    "Discuss the powers and functions of the National Commission for Scheduled Castes.",
    "What is the significance of the 105th Amendment to the Indian Constitution?",
    "Explain the concept of judicial accountability in India.",
    "What are the qualifications required to become a member of a State Legislative Council?",
    "Discuss the powers and functions of the Union Public Service Commission.",
    "What is the procedure for the amendment of the Constitution to change the boundaries of states?",
    "Explain the concept of legislative privilege with examples.",
    "What are the powers and functions of the State Election Commission?",
    "Discuss the role of the Chief Minister in the state government.",
    "What is the procedure for removal of the Speaker of the Lok Sabha?",
    "Explain the concept of the Rule of Law in the Indian context.",
    "What are the powers and functions of the National Commission for Scheduled Tribes?",
    "Discuss the significance of the 98th Amendment to the Indian Constitution.",
    "What is the procedure for appointment of the Attorney General of a State?",
    "Explain the concept of double jeopardy as provided in the Indian Constitution.",
    "What are the grounds for the dissolution of a State Legislative Assembly?",
    "Discuss the powers and functions of the Union Territories in India.",
    "What is the procedure for appointment of the Advocate General of a State?",
    "Explain the concept of reservation in promotions for Scheduled Castes and Scheduled Tribes.",
    "What are the qualifications required to become a member of a Municipal Corporation?",
    "Discuss the powers and functions of the State Human Rights Commission.",
    "What is the procedure for the creation of a new state in India?",
    "Explain the concept of legal aid in India.",
    "What are the powers and functions of the Central Information Commission?",
    "Discuss the significance of the 124th Amendment to the Indian Constitution.",
    "What is the procedure for the removal of a Chief Minister?",
    "Explain the concept of President's pleasure in the context of the appointment of Governors.",
    "What are the powers and functions of the District Collector?",
    "Discuss the provisions regarding the abolition and creation of Legislative Councils in states.",
    "What is the procedure for the appointment of the Chief Minister in a state?",
    "Explain the concept of public interest litigation (PIL) in India.",
    "What are the powers and functions of the State Human Rights Commission?",
    "Discuss the provisions regarding the Official Language of India.",
    "What is the procedure for the imposition of Governor's Rule in a state?",
    "Explain the concept of writ jurisdiction of the High Courts.",
    "What are the powers and functions of the State Finance Commission?",
    "Discuss the provisions regarding the suspension of fundamental rights during emergencies.",
    "What is the procedure for the appointment of the Chief Justice of India?",
    "Explain the concept of quorum in the context of parliamentary proceedings.",
    "What are the powers and functions of the State Legislative Council?",
    "Discuss the provisions regarding the establishment and jurisdiction of District Courts.",
    "What is the procedure for the appointment of the Chairman of the National Human Rights Commission?",
    "Explain the concept of judicial independence in India.",
    "What are the powers and functions of the State Public Service Commission?",
    "Discuss the provisions regarding the declaration of a territory as a Union Territory.",
    "What is the procedure for the removal of the Chief Justice of a High Court?",
    "Explain the concept of privilege motion in the context of parliamentary proceedings.",
    "What are the powers and functions of the State Election Commission?",
    "Discuss the provisions regarding the disqualification of members of Parliament and state legislatures.",
    "What is the procedure for the appointment of the Chief Information Commissioner?",
    "Explain the concept of vote of no confidence in the context of parliamentary democracy.",
    "What are the powers and functions of the District Magistrate?",
    "Discuss the provisions regarding the establishment and jurisdiction of the Supreme Court of India.",
    "What is the procedure for the removal of a Judge of the High Court?",
    "Explain the concept of judicial precedent in India.",
    "What are the powers and functions of the State Human Rights Commission?",
    "Discuss the provisions regarding the establishment and jurisdiction of Family Courts.",
    "What is the procedure for the removal of the Chief Election Commissioner?",
    "Explain the concept of separation of powers in the Indian Constitution.",
    "What are the powers and functions of the Central Administrative Tribunal?",
    "Discuss the provisions regarding the establishment and jurisdiction of the National Green Tribunal.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Scheduled Castes?",
    "Explain the concept of judicial review in India.",
    "What are the powers and functions of the State Legislative Assembly?",
    "Discuss the provisions regarding the establishment and jurisdiction of the Central Administrative Tribunal.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Scheduled Tribes?",
    "Explain the concept of federalism in India.",
    "What are the powers and functions of the State Legislative Council?",
    "Discuss the provisions regarding the establishment and jurisdiction of the Central Information Commission.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Backward Classes?",
    "Explain the concept of judicial activism in India.",
    "What are the powers and functions of the Union Territories in India?",
    "Discuss the provisions regarding the establishment and jurisdiction of the National Human Rights Commission.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Women?",
    "Explain the concept of rule of law in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the provisions regarding the establishment and jurisdiction of the State Human Rights Commission.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Protection of Child Rights?",
    "Explain the concept of due process of law in India.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the provisions regarding the establishment and jurisdiction of the National Commission for Safai Karamcharis.",
    "What is the procedure for the removal of the Chairperson of the National Commission for Minorities?",
    "Explain the concept of judicial restraint in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the provisions regarding the establishment and jurisdiction of the National Commission for Backward Classes."
     "What are the responsibilities outlined as fundamental duties in the Indian Constitution?",
    "In what manner does judicial activism manifest within the Indian judiciary?",
    "How does the Basic Structure Doctrine hold significance within Indian constitutional law?",
    "Explore the roles and authorities of the State Legislative Assembly.",
    "Under what conditions can an individual lose their Indian citizenship?",
    "Outline the process for appointing and dismissing a Chief Justice of a High Court.",
    "What criteria lead to disqualification of a State Legislative Assembly member?",
    "Detail the functions of the Finance Commission in India.",
    "Can citizens directly approach the Supreme Court to enforce fundamental rights?",
    "Explain the concept of cooperative federalism within the Indian Constitution.",
    "Elaborate on the roles and responsibilities of the State Public Service Commission.",
    "Discuss the provisions regarding the establishment and authority of High Courts in India.",
    "How is President's Rule imposed within a state, and what is its procedure?",
    "Describe the steps for impeaching the Vice President of India.",
    "What provisions exist for reserved seats for Scheduled Castes and Scheduled Tribes in the Lok Sabha?",
    "Examine the powers and functions of the National Commission for Scheduled Castes.",
    "What is the importance of the 105th Amendment to the Indian Constitution?",
    "Define judicial accountability and its implications in India.",
    "What qualifications are necessary for State Legislative Council membership?",
    "Discuss the roles and functions of the Union Public Service Commission.",
    "How is the Constitution amended to alter state boundaries?",
    "Describe legislative privilege using examples.",
    "What are the powers and functions of the State Election Commission?",
    "Explore the responsibilities of a Chief Minister in state governance.",
    "Outline the process for removing the Speaker of the Lok Sabha.",
    "Define the Rule of Law in the context of India.",
    "Examine the powers and functions of the National Commission for Scheduled Tribes.",
    "Assess the significance of the 98th Amendment to the Indian Constitution.",
    "How is the Attorney General of a State appointed?",
    "Define double jeopardy as per the Indian Constitution.",
    "What circumstances lead to the dissolution of a State Legislative Assembly?",
    "Discuss the roles and functions of Union Territories in India.",
    "How is Governor's Rule imposed in a state, and what is its procedure?",
    "Explain the High Courts' writ jurisdiction.",
    "Discuss the State Finance Commission's roles and functions.",
    "Analyze the provisions for suspending fundamental rights during emergencies.",
    "Describe the process for appointing the Chief Justice of India.",
    "Explain quorum in parliamentary proceedings.",
    "Examine the powers and functions of the State Legislative Assembly.",
    "Discuss the provisions for establishing and determining the Supreme Court's jurisdiction in India.",
    "Outline the process for appointing the National Human Rights Commission Chairman.",
    "Define judicial independence and its significance in India.",
    "Examine the powers and functions of the State Public Service Commission.",
    "Discuss the provisions for declaring a territory as a Union Territory.",
    "Describe the process for removing a High Court Judge.",
    "Explain privilege motion in parliamentary proceedings.",
    "Examine the powers and functions of the State Election Commission.",
    "Discuss the provisions for disqualifying Members of Parliament and state legislatures.",
    "Describe the process for appointing the Chief Information Commissioner.",
    "Explain the concept of a vote of no confidence in parliamentary democracy.",
    "Assess the powers and functions of the District Magistrate.",
    "Discuss the provisions for establishing and determining the Supreme Court's jurisdiction in India.",
    "Describe the process for removing a High Court Chief Justice.",
    "Explain judicial precedent and its implications in India.",
    "Examine the powers and functions of the State Human Rights Commission.",
    "Discuss the provisions for establishing and determining Family Courts' jurisdiction.",
    "Describe the process for removing the Chief Election Commissioner.",
    "Define separation of powers as outlined in the Indian Constitution.",
    "Assess the powers and functions of the Central Administrative Tribunal.",
    "Discuss the provisions for establishing and determining the National Green Tribunal's jurisdiction.",
    "Describe the process for removing the National Commission for Scheduled Castes Chairperson.",
    "Explain judicial review and its application in India.",
    "Examine the powers and functions of the State Legislative Assembly.",
    "Discuss the provisions for establishing and determining the Central Administrative Tribunal's jurisdiction.",
    "Describe the process for removing the National Commission for Scheduled Tribes Chairperson.",
    "Define federalism and its implications in India.",
    "Examine the powers and functions of the State Legislative Council.",
    "Discuss the provisions for establishing and determining the Central Information Commission's jurisdiction.",
    "Describe the process for removing the National Commission for Backward Classes Chairperson.",
    "Explain judicial activism and its manifestations in India.",
    "Examine the powers and functions of the Union Territories in India.",
    "Discuss the provisions for establishing and determining the National Human Rights Commission's jurisdiction.",
    "Describe the process for removing the National Commission for Women Chairperson.",
    "Define the rule of law and its application in the Indian Constitution.",
    "Examine the powers and functions of the National Commission for Minorities.",
    "Discuss the provisions for establishing and determining the State Human Rights Commission's jurisdiction.",
    "Describe the process for removing the National Commission for Protection of Child Rights Chairperson.",
    "Explain due process of law and its application in India.",
    "Examine the powers and functions of the National Commission for Women.",
    "Discuss the provisions for establishing and determining the National Commission for Safai Karamcharis' jurisdiction.",
    "Describe the process for removing the National Commission for Minorities Chairperson.",
    "Define judicial restraint and its application in India.",
    "Assess the powers and functions of the National Commission for Protection of Child Rights.",
    "Discuss the provisions for establishing and determining the National Commission for Backward Classes' jurisdiction.",
     "What are the responsibilities outlined in the fundamental duties of the Indian Constitution?",
    "How is judicial activism understood within the framework of the Indian judiciary?",
    "What is the importance of the Basic Structure Doctrine in Indian constitutional jurisprudence?",
    "Outline the powers and functions of the State Legislative Assembly.",
    "Under what circumstances can Indian citizenship be revoked for a citizen?",
    "Describe the process for appointing and dismissing a Chief Justice of a High Court.",
    "What criteria lead to disqualification of a member of a State Legislative Assembly?",
    "Explain the role played by the Finance Commission in India.",
    "Can Indian citizens directly approach the Supreme Court to enforce their fundamental rights?",
    "Define cooperative federalism in the context of the Indian Constitution.",
    "Detail the powers and functions of the State Public Service Commission.",
    "Explain the setup and jurisdiction of High Courts in India.",
    "How is President's Rule imposed in a state, and what are its implications?",
    "What steps are involved in impeaching the Vice President of India?",
    "How are seats reserved for Scheduled Castes and Scheduled Tribes allocated in the Lok Sabha?",
    "Discuss the functions and powers of the National Commission for Scheduled Castes.",
    "Highlight the significance of the 105th Amendment to the Indian Constitution.",
    "Elaborate on the concept of judicial accountability within the Indian legal system.",
    "What qualifications are necessary to become a member of a State Legislative Council?",
    "Explore the roles and responsibilities of the Union Public Service Commission.",
    "How is the Constitution amended to alter state boundaries, and what is the process involved?",
    "Explain legislative privilege using relevant examples.",
    "What are the duties and powers of the State Election Commission?",
    "Describe the Chief Minister's role within the state government.",
    "Outline the procedure for removing the Speaker of the Lok Sabha.",
    "Define the Rule of Law as it pertains to India.",
    "Discuss the functions and powers of the National Commission for Scheduled Tribes.",
    "Examine the significance of the 98th Amendment to the Indian Constitution.",
    "How is the Attorney General of a State appointed?",
    "Explain the concept of double jeopardy within the Indian legal system.",
    "What leads to the dissolution of a State Legislative Assembly?",
    "What roles and powers do Union Territories possess in India?",
    "Detail the process for appointing a State's Advocate General.",
    "Explain the reservation in promotions for Scheduled Castes and Scheduled Tribes.",
    "What are the eligibility criteria for membership in a Municipal Corporation?",
    "Examine the roles and powers of the State Human Rights Commission.",
    "What procedures are followed to create a new state in India?",
    "Define and discuss legal aid in the Indian context.",
    "Outline the roles and functions of the Central Information Commission.",
    "Analyze the significance of the 124th Amendment to the Indian Constitution.",
    "How is a Chief Minister removed from office?",
    "Clarify the concept of the President's pleasure in the appointment of Governors.",
    "Explain the powers and duties of the District Collector.",
    "Discuss the provisions for creating and abolishing Legislative Councils in states.",
    "Detail the process for appointing a Chief Minister in a state.",
    "Define and discuss public interest litigation (PIL) in India.",
    "What are the powers and functions of the State Human Rights Commission?",
    "Describe the Official Language provisions in the Indian Constitution.",
    "Explain the procedure for imposing Governor's Rule in a state.",
    "Describe the writ jurisdiction of the High Courts.",
    "What are the roles and functions of the State Finance Commission?",
    "Discuss the provisions for suspending fundamental rights during emergencies.",
    "How is the Chief Justice of India appointed?",
    "Define the concept of quorum in parliamentary proceedings.",
    "What are the powers and functions of the State Legislative Assembly?",
    "Discuss the provisions for establishing and defining the jurisdiction of District Courts.",
    "How is the Chairman of the National Human Rights Commission appointed?",
    "Define judicial independence and its significance in India.",
    "What are the powers and functions of the State Public Service Commission?",
    "Discuss the provisions for declaring a territory as a Union Territory.",
    "Detail the process for removing a High Court Judge from office.",
    "Explain the concept of privilege motion in parliamentary proceedings.",
    "What are the powers and functions of the State Election Commission?",
    "Discuss the provisions for disqualifying members of Parliament and state legislatures.",
    "Explain the process for appointing the Chief Information Commissioner.",
    "Define and discuss the vote of no confidence in parliamentary democracy.",
    "What are the powers and functions of the District Magistrate?",
    "Discuss the provisions for establishing and defining the jurisdiction of the Supreme Court of India.",
    "How is a High Court Judge removed from office?",
    "Explain the concept of judicial precedent in the Indian legal system.",
    "What are the powers and functions of the State Human Rights Commission?",
    "Discuss the provisions for establishing and defining the jurisdiction of Family Courts.",
    "How is the Chief Election Commissioner removed from office?",
    "Explain the concept of separation of powers in the Indian Constitution.",
    "What are the powers and functions of the Central Administrative Tribunal?",
    "Discuss the provisions for establishing and defining the jurisdiction of the National Green Tribunal.",
    "How is the Chairperson of the National Commission for Scheduled Castes removed?",
    "Explain the concept of judicial review in the Indian legal system.",
    "What are the powers and functions of the State Legislative Assembly?",
    "Discuss the provisions for establishing and defining the jurisdiction of the Central Administrative Tribunal.",
    "How is the Chairperson of the National Commission for Scheduled Tribes removed?",
    "Explain the concept of federalism in India.",
    "What are the powers and functions of the State Legislative Council?",
    "Discuss the provisions for establishing and defining the jurisdiction of the Central Information Commission.",
    "How is the Chairperson of the National Commission for Backward Classes removed?",
    "Explain the concept of judicial activism in India.",
    "What are the powers and functions of the Union Territories in India?",
    "Discuss the provisions for establishing and defining the jurisdiction of the National Human Rights Commission.",
    "How is the Chairperson of the National Commission for Women removed?",
    "Define the concept of the rule of law in the Indian Constitution.",
    "What are the powers and functions of the National Commission for Minorities?",
    "Discuss the provisions for establishing and defining the jurisdiction of the State Human Rights Commission.",
    "How is the Chairperson of the National Commission for Protection of Child Rights removed?",
    "Explain the concept of due process of law in India.",
    "What are the powers and functions of the National Commission for Women?",
    "Discuss the provisions for establishing and defining the jurisdiction of the National Commission for Safai Karamcharis.",
    "How is the Chairperson of the National Commission for Minorities removed?",
    "Explain the concept of judicial restraint in India.",
    "What are the powers and functions of the National Commission for Protection of Child Rights?",
    "Discuss the provisions for establishing and defining the jurisdiction of the National Commission for Backward Classes.",
    "What are the fundamental rights guaranteed by the Indian Constitution?",
    "Can you explain the concept of judicial review in India?",
    "What is the procedure for amending the Indian Constitution?",
    "How does the Indian Constitution protect the rights of minorities?",
    "What is the difference between fundamental rights and directive principles of state policy?",
    "Can you explain the concept of federalism in the Indian Constitution?",
    "What are the qualifications for becoming the President of India?",
    "What are the powers and functions of the Prime Minister of India?",
    "How is the President of India elected?",
    "Can you explain the concept of parliamentary sovereignty in India?",
    "What is the significance of the Preamble to the Indian Constitution?",
    "How does the Indian Constitution protect freedom of speech and expression?",
    "Can you explain the concept of separation of powers in the Indian Constitution?",
    "What is the procedure for impeachment of the President of India?",
    "How are the members of the Rajya Sabha elected?",
    "Can you explain the concept of judicial activism in India?",
    "What is the role of the Attorney General of India?",
    "How does the Indian Constitution protect the rights of women?",
    "Can you explain the concept of secularism in the Indian Constitution?",
    "What is the composition and jurisdiction of the Supreme Court of India?",
    "How does the Indian Constitution protect the rights of the LGBTQ+ community?",
    "What are the fundamental duties prescribed by the Indian Constitution?",
    "Can you explain the concept of reservation in India?",
    "What is the procedure for the removal of a Supreme Court judge?",
    "How does the Indian Constitution protect the rights of children?",
    "Can you explain the concept of writs in the Indian Constitution?",
    "What is the procedure for the dissolution of the Lok Sabha?",
    "How does the Indian Constitution protect the rights of the differently-abled?",
    "Can you explain the concept of federal supremacy in India?",
    "What is the procedure for the appointment of judges to the Supreme Court?",
    "How does the Indian Constitution protect the rights of indigenous tribes?",
    "Can you explain the concept of parliamentary privilege in India?",
    "What is the role of the Election Commission of India?",
    "How does the Indian Constitution protect the rights of religious minorities?",
    "Can you explain the concept of preventive detention in India?",
    "What is the role of the Chief Justice of India?",
    "How does the Indian Constitution protect the rights of prisoners?",
    "Can you explain the concept of due process of law in India?",
    "What is the procedure for the removal of a Governor?",
    "How does the Indian Constitution protect the rights of the elderly?",
    "Can you explain the concept of double jeopardy in India?",
    "What is the procedure for the impeachment of a Supreme Court judge?",
    "How does the Indian Constitution protect the rights of refugees and asylum seekers?",
    "Can you explain the concept of judicial independence in India?",
    "What is the procedure for the enactment of a constitutional amendment?",
    "How does the Indian Constitution protect the rights of the accused?",
    "Can you explain the concept of public interest litigation (PIL) in India?",
    "What is the procedure for the appointment of the Chief Justice of India?",
    "How does the Indian Constitution protect the rights of whistleblowers?",
    "Can you explain the concept of sedition in India?",
    "What is the procedure for the removal of a High Court judge?",
    "How does the Indian Constitution protect the rights of victims of crime?",
    "Can you explain the concept of legal aid in India?",
    "What is the procedure for the dissolution of a State Legislative Assembly?",
    "How does the Indian Constitution protect the rights of migrant workers?",
    "Can you explain the concept of contempt of court in India?",
    "What is the procedure for the appointment of the Chief Election Commissioner?",
    "How does the Indian Constitution protect the rights of tenants?",
    "Can you explain the concept of extradition in India?",
    "What is the procedure for the removal of the Chief Election Commissioner?",
    "How does the Indian Constitution protect the rights of the LGBTQ+ community in employment?",
    "Can you explain the concept of habeas corpus in India?",
    "What is the procedure for the removal of the Chairperson of the National Human Rights Commission?",
    "How does the Indian Constitution protect the rights of persons with disabilities in education?",
    "Can you explain the concept of money bill in India?",
    "What is the procedure for the dissolution of a Municipal Corporation?",
    "How does the Indian Constitution protect the rights of indigenous tribes in land ownership?",
    "Can you explain the concept of sedition in India?",
    "What is the procedure for the removal of the Chairperson of the National Commission for Women?",
    "How does the Indian Constitution protect the rights of religious minorities in educational institutions?",
    "Can you explain the concept of preventive detention in India?",
    "What is the procedure for the dissolution of a Municipal Corporation?",
    "How does the Indian Constitution protect the rights of refugees and asylum seekers?",
    "Can you explain the concept of contempt of court in India?",
    "What is the procedure for the removal of the Chairperson of the National Commission for Minorities?",
    "How does the Indian Constitution protect the rights of farmers in land acquisition?",
    "Can you explain the concept of legal aid in India?",
    "What is the procedure for the dissolution of a Gram Panchayat?",
    "How does the Indian Constitution protect the rights of persons with disabilities in employment?",
    "Can you explain the concept of habeas corpus in India?",
    "What is the procedure for the removal of the Chairperson of the National Commission for Scheduled Castes?",
    "How does the Indian Constitution protect the rights of women in the workplace?",
    "Can you explain the concept of money bill in India?",
    "What is the procedure for the dissolution of a Zilla Parishad?",
    "How does the Indian Constitution protect the rights of transgender individuals?",
    "Can you explain the concept of preventive detention in India?",
    "What is the procedure for the removal of the Chairperson of the National Commission for Backward Classes?",
    "How does the Indian Constitution protect the rights of children in adoption?",
    "Can you explain the concept of contempt of court in India?",
    "What is the procedure for the dissolution of a Municipal Corporation?",
    "How does the Indian Constitution protect the rights of victims of domestic violence?",
    "What fundamental rights does the Indian Constitution guarantee?",
    "Could you elaborate on the Indian judiciary's power of review?",
    "How can the Indian Constitution be amended?",
    "How does the Indian Constitution safeguard minority rights?",
    "What distinguishes fundamental rights from directive principles in the Indian Constitution?",
    "Can you explain how federalism is embodied in the Indian Constitution?",
    "What are the eligibility criteria for the Indian presidency?",
    "What roles and responsibilities does the Indian Prime Minister hold?",
    "What is the process for electing the President of India?",
    "Explain the concept of parliamentary supremacy in India.",
    "What significance does the Preamble hold in the Indian Constitution?",
    "How is freedom of speech and expression protected under the Indian Constitution?",
    "Describe the principle of separation of powers in the Indian context.",
    "How can the President of India be impeached?",
    "How are members of the Rajya Sabha chosen?",
    "Explain the concept of judicial activism in India.",
    "What are the duties of the Attorney General of India?",
    "How does the Indian Constitution protect the rights of women?",
    "Define secularism as per the Indian Constitution.",
    "Detail the composition and jurisdiction of the Supreme Court of India.",
    "How does the Indian Constitution safeguard LGBTQ+ rights?",
    "What fundamental duties does the Indian Constitution outline?",
    "Clarify the concept of reservation in India.",
    "What's the process for removing a Supreme Court judge?",
    "How does the Indian Constitution protect children's rights?",
    "Explain the significance of writs in the Indian Constitution.",
    "Outline the process for dissolving the Lok Sabha.",
    "How does the Indian Constitution protect the rights of the differently-abled?",
    "Elaborate on the concept of federal supremacy in India.",
    "How are Supreme Court judges appointed?",
    "How does the Indian Constitution protect the rights of indigenous tribes?",
    "Explain the concept of parliamentary privilege in India.",
    "What role does the Election Commission of India play?",
    "How does the Indian Constitution protect the rights of religious minorities?",
    "Define preventive detention in the Indian context.",
    "What is the role of the Chief Justice of India?",
    "How does the Indian Constitution protect prisoners' rights?",
    "Explain the concept of due process of law in India.",
    "What's the procedure for removing a Governor?",
    "How does the Indian Constitution protect the rights of the elderly?",
    "Explain the concept of double jeopardy in India.",
    "How can a Supreme Court judge be impeached?",
    "How does the Indian Constitution protect the rights of refugees and asylum seekers?",
    "Define judicial independence in the Indian context.",
    "Outline the process for enacting a constitutional amendment.",
    "How does the Indian Constitution protect the rights of the accused?",
    "Explain the concept of public interest litigation (PIL) in India.",
    "How is the Chief Justice of India appointed?",
    "How does the Indian Constitution protect whistleblowers' rights?",
    "Define sedition as per the Indian Constitution.",
    "What's the process for removing a High Court judge?",
    "How does the Indian Constitution protect victims' rights?",
    "Explain the concept of legal aid in India.",
    "Detail the process for dissolving a State Legislative Assembly.",
    "How does the Indian Constitution protect the rights of migrant workers?",
    "Explain the concept of contempt of court in India.",
    "What's the process for appointing the Chief Election Commissioner?",
    "How does the Indian Constitution protect tenants' rights?",
    "Define extradition in the Indian context.",
    "What's the process for removing the Chief Election Commissioner?",
    "How does the Indian Constitution protect consumers' rights?",
    "Explain the right to privacy as per the Indian Constitution.",
    "Detail the process for dissolving a Municipal Corporation.",
    "How does the Indian Constitution protect animal rights?",
    "Define defamation under the Indian Constitution.",
    "What's the process for removing the Chief Information Commissioner?",
    "How does the Indian Constitution protect farmers' rights?",
    "Explain the concept of contempt of Parliament in India.",
    "Detail the process for dissolving a Gram Panchayat.",
    "How does the Indian Constitution protect LGBTQ+ rights in employment?",
    "Explain the concept of habeas corpus in India.",
    "What's the process for removing the Chairperson of the National Human Rights Commission?",
    "How does the Indian Constitution protect persons with disabilities' rights in education?",
    "Define a money bill in the Indian context.",
    "Detail the process for dissolving a Zilla Parishad.",
    "How does the Indian Constitution protect indigenous tribes' rights in land ownership?",
    "Define sedition under the Indian Constitution.",
    "What's the process for removing the Chairperson of the National Commission for Women?",
    "How does the Indian Constitution protect religious minorities' rights in educational institutions?",
    "Define preventive detention in the Indian context.",
    "What's the process for dissolving a Municipal Corporation?",
    "How does the Indian Constitution protect refugees and asylum seekers' rights?",
    "Explain the concept of contempt of court in India.",
    "What's the process for removing the Chairperson of the National Commission for Minorities?",
    "How does the Indian Constitution protect farmers' rights in land acquisition?",
    "Explain the concept of legal aid in India.",
    "Detail the process for dissolving a Gram Panchayat.",
    "How does the Indian Constitution protect persons with disabilities' rights in employment?",
    "Explain the concept of habeas corpus in India.",
    "What's the process for removing the Chairperson of the National Commission for Scheduled Castes?",
    "How does the Indian Constitution protect women's rights in the workplace?",
    "Define a money bill in the Indian context.",
    "Detail the process for dissolving a Zilla Parishad.",
    "How does the Indian Constitution protect transgender individuals' rights?",
    "Define preventive detention in the Indian context.",
    "What's the process for removing the Chairperson of the National Commission for Backward Classes?",
    "How does the Indian Constitution protect children's rights in adoption?",
    "Explain the concept of contempt of court in India.",
    "What's the process for dissolving a Municipal Corporation?",
    "How does the Indian Constitution protect victims of domestic violence' rights?"
      "How does the Indian Constitution define the concept of citizenship?",
    "Can you explain the role and powers of the Vice President of India?",
    "What is the procedure for the removal of a member of the State Legislative Council?",
    "How does the Indian Constitution ensure the independence of the Election Commission?",
    "Can you explain the concept of territorial jurisdiction of courts in India?",
    "What is the procedure for the dissolution of a Union Territory Legislative Assembly?",
    "How does the Indian Constitution protect the rights of prisoners during detention?",
    "Can you explain the procedure for the removal of a member of a State Public Service Commission?",
    "What are the qualifications required to become a member of the Rajya Sabha?",
    "How does the Indian Constitution protect the rights of persons accused of crimes?",
    "Can you explain the significance of the Mandal Commission report in Indian constitutional history?",
    "What is the procedure for the appointment of the Chief Minister of a state?",
    "How does the Indian Constitution provide for the protection of minority languages?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Bureau of Investigation (CBI) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of internally displaced persons?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Legislative Council in a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of communal violence?",
    "Can you explain the procedure for the removal of a member of a State Women's Commission?",
    "What is the significance of the Mandal Commission report in Indian constitutional history?",
    "How does the Indian Constitution provide for the protection of the rights of linguistic minorities?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the State Election Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of hate crimes?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Vigilance Commission in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of refugees?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the State Public Service Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human trafficking?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Administrative Tribunal (CAT) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of cybercrimes?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the State Women's Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human rights violations?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Bureau of Investigation (CBI) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of environmental degradation?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Legislative Council in a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of honor crimes?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Vigilance Commission in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of domestic violence?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the Advocate General of a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of child labor?",
    "Can you explain the procedure for the removal of a member of a State Women's Commission?",
    "What is the role of the Central Pollution Control Board (CPCB) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human rights violations?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the State Election Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of honor crimes?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Administrative Tribunal (CAT) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of domestic violence?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Advocate General of a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of child labor?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Pollution Control Board (CPCB) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human trafficking?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the State Women's Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of sexual harassment?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Bureau of Investigation (CBI) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of environmental degradation?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Legislative Council in a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of honor crimes?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Vigilance Commission in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of domestic violence?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the Advocate General of a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of child labor?",
    "Can you explain the procedure for the removal of a member of a State Women's Commission?",
    "What is the role of the Central Pollution Control Board (CPCB) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human rights violations?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the State Election Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of honor crimes?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Administrative Tribunal (CAT) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of domestic violence?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Advocate General of a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of child labor?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Pollution Control Board (CPCB) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human trafficking?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the State Women's Commission?",
    "How does the Indian Constitution provide for the protection of the rights of victims of sexual harassment?",
    "Can you explain the procedure for the removal of a member of a State Commission for Women?",
    "What is the role of the Central Bureau of Investigation (CBI) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of environmental degradation?",
    "Can you explain the procedure for the appointment of the Chief Justice of a High Court?",
    "What are the powers and functions of the Legislative Council in a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of honor crimes?",
    "Can you explain the procedure for the removal of a member of a State Human Rights Commission?",
    "What is the role of the Central Vigilance Commission in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of domestic violence?",
    "Can you explain the procedure for the appointment of the Chief Justice of India?",
    "What are the powers and functions of the Advocate General of a state?",
    "How does the Indian Constitution provide for the protection of the rights of victims of child labor?",
    "Can you explain the procedure for the removal of a member of a State Women's Commission?",
    "What is the role of the Central Pollution Control Board (CPCB) in India's legal system?",
    "How does the Indian Constitution provide for the protection of the rights of victims of human rights violations?"

]

