questions = [
    "What are the legal requirements for a marriage to be valid in India?",
    "What is the minimum age for marriage in India?",
    "Can a marriage be annulled in India? If so, under what circumstances?",
    "What are the grounds for divorce in India?",
    "How is property divided in a divorce in India?",
    "What are the rights of women in a marriage under Indian law?",
    "What are the rights of men in a marriage under Indian law?",
    "Are prenuptial agreements legally binding in India?",
    "How does religion affect marriage laws in India?",
    "Can a foreigner marry an Indian citizen in India?",
    "What are the legal implications of a court marriage in India?",
    "Is same-sex marriage legal in India?",
    "What are the legal rights of children born out of wedlock in India?",
    "Can a person marry more than one spouse in India?",
    "How does caste affect marriage laws in India?",
    "What is the procedure for registering a marriage in India?",
    "Can a marriage be registered after the wedding ceremony in India?",
    "Are interfaith marriages legally recognized in India?",
    "What is the legal status of common-law marriages in India?",
    "How does adultery affect divorce proceedings in India?",
    "Can a person change their name after marriage in India?",
    "What is the punishment for child marriage in India?",
    "Can a marriage be voided if one party was forced into it?",
    "Are there any restrictions on inter-caste marriages in India?",
    "Can a person marry their cousin in India?",
    "What is the legal age difference for marriage in India?",
    "Are there any legal consequences for marrying a minor in India?",
    "How does religion affect inheritance laws in marriage in India?",
    "Can a married couple adopt a child in India?",
    "What are the legal rights of a wife regarding her husband's property in India?",
    "Can a person marry someone from a different nationality in India?",
    "How does domestic violence affect divorce proceedings in India?",
    "What is the procedure for obtaining a marriage certificate in India?",
    "Can a marriage be dissolved if one spouse is mentally incapacitated?",
    "What are the legal rights of a husband regarding his wife's property in India?",
    "Can a person marry a non-resident Indian in India?",
    "What are the legal rights of transgender individuals regarding marriage in India?",
    "Can a marriage be annulled if one spouse is discovered to be already married?",
    "How does dowry affect marriage laws in India?",
    "Can a person marry someone from a different caste in India?",
    "Are there any legal consequences for refusing to marry in India?",
    "How does polygamy affect marriage laws in India?",
    "Can a person marry someone from a different socioeconomic background in India?",
    "What are the legal rights of a widow regarding her deceased husband's property in India?",
    "Can a person marry their deceased spouse's sibling in India?",
    "What are the legal rights of a widower regarding his deceased wife's property in India?",
    "Can a marriage be annulled if it was entered into under duress?",
    "How does infertility affect marriage laws in India?",
    "Can a person marry someone from a different religion without converting in India?",
    "What are the legal consequences of marrying without parental consent in India?",
    "Can a marriage be annulled if one spouse concealed important information before marriage?",
    "How does remarriage affect inheritance rights in India?",
    "Can a person marry someone with a criminal record in India?",
    "What are the legal rights of a married couple regarding surrogacy in India?",
    "Can a person marry someone from a different language-speaking community in India?",
    "How does mental illness affect marriage laws in India?",
    "Can a person marry someone from a different ethnicity in India?",
    "What are the legal rights of a married couple regarding adoption in India?",
    "Can a person marry someone from a different state in India?",
    "How does bankruptcy affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was underage at the time of marriage?",
    "What are the legal rights of a married couple regarding medical decisions in India?",
    "Can a person marry someone with a physical disability in India?",
    "How does addiction affect marriage laws in India?",
    "Can a marriage be annulled if one spouse misrepresented their identity?",
    "What are the legal rights of a married couple regarding property ownership in India?",
    "Can a person marry someone with a terminal illness in India?",
    "How does incarceration affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was impotent at the time of marriage?",
    "What are the legal rights of a married couple regarding insurance benefits in India?",
    "Can a person marry someone with a history of domestic violence in India?",
    "How does a mental health diagnosis affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was under the influence of drugs or alcohol at the time of marriage?",
    "What are the legal rights of a married couple regarding tax benefits in India?",
    "Can a person marry someone with a history of infidelity in India?",
    "How does a physical disability affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was mentally incapacitated at the time of marriage?",
    "What are the legal rights of a married couple regarding pension benefits in India?",
    "Can a person marry someone with a significant age gap in India?",
    "How does financial instability affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was coerced into marriage by their family?",
    "What are the legal rights of a married couple regarding social security benefits in India?",
    "Can a person marry someone with different political beliefs in India?",
    "How does immigration status affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was misled about the other's financial status?",
    "What are the legal rights of a married couple regarding healthcare benefits in India?",
    "Can a person marry someone with different cultural beliefs in India?",
    "How does employment status affect marriage laws in India?",
    "Can a marriage be annulled if one spouse concealed their criminal history?",
    "What are the legal rights of a married couple regarding child custody in India?",
    "Can a person marry someone with a different level of education in India?",
    "How does a lack of communication affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was not of sound mind at the time of marriage?",
    "What are the legal rights of a married couple regarding alimony in India?",
    "Can a person marry someone with a different lifestyle in India?",
    "How does cultural assimilation affect marriage laws in India?",
    "Can a marriage be annulled if one spouse was physically abusive before marriage?",
    "What are the legal rights of a married couple regarding joint bank accounts in India?",
    "Can a person marry someone with a different sexual orientation in India?",
    "How does religious conversion affect marriage laws in India?",
   "What constitutes cybercrime under Indian law?",
    "What are the penalties for cybercrimes in India?",
    "How does Indian law define hacking?",
    "Is hacking into someone's social media account illegal in India?",
    "What are the legal implications of spreading viruses or malware in India?",
    "Can someone be prosecuted for phishing scams in India?",
    "Are there specific laws regarding cyberbullying in India?",
    "What actions constitute online harassment under Indian law?",
    "How can individuals protect themselves from online harassment in India?",
    "What are the legal consequences of identity theft in India?",
    "Can individuals be held liable for sharing sensitive information online in India?",
    "What are the legal obligations for companies handling user data in India?",
    "How does Indian law address data breaches?",
    "Are there specific regulations for e-commerce websites in India regarding consumer data protection?",
    "Can someone be prosecuted for online defamation in India?",
    "What actions constitute online defamation under Indian law?",
    "How does Indian law address revenge porn or non-consensual sharing of intimate images?",
    "What are the legal implications of cyberstalking in India?",
    "Can employers monitor their employees' online activities legally in India?",
    "How does Indian law address cyber espionage?",
    "Are there specific laws regarding cyberterrorism in India?",
    "Can individuals be prosecuted for hacking into government systems in India?",
    "How does Indian law address online financial fraud?",
    "What are the legal consequences of copyright infringement online in India?",
    "Can someone be prosecuted for pirating software or media in India?",
    "How does Indian law address online gambling?",
    "What are the regulations for cryptocurrency trading in India?",
    "Can someone be prosecuted for online drug trafficking in India?",
    "How does Indian law address online human trafficking?",
    "Are there specific regulations for online dating platforms in India?",
    "Can someone be prosecuted for cybersquatting in India?",
    "What are the legal implications of distributed denial of service (DDoS) attacks in India?",
    "How does Indian law address online hate speech?",
    "Can individuals be prosecuted for sharing fake news online in India?",
    "What are the legal consequences of creating or distributing deep fake videos in India?",
    "Can someone be held liable for cyberbullying a minor in India?",
    "How does Indian law address online scams targeting senior citizens?",
    "Are there specific regulations for online medical consultation platforms in India?",
    "Can individuals be prosecuted for spreading misinformation about diseases online in India?",
    "What are the legal obligations for social media platforms regarding content moderation in India?",
    "Can someone be prosecuted for hacking into a company's database in India?",
    "How does Indian law address online terrorism financing?",
    "Can individuals be prosecuted for spreading rumors that lead to violence online in India?",
    "What are the regulations for online political campaigning in India?",
    "Can someone be held liable for cyberbullying a public figure in India?",
    "How does Indian law address online wildlife trafficking?",
    "Can individuals be prosecuted for online stalking in India?",
    "What are the legal consequences of leaking classified information online in India?",
    "Can someone be prosecuted for cyber espionage against foreign entities in India?",
    "How does Indian law address online harassment based on gender or sexual orientation?",
    "Are there specific regulations for online job portals regarding user data protection in India?",
    "Can individuals be prosecuted for hacking into educational institutions' systems in India?",
    "What are the legal implications of cyber warfare under Indian law?",
    "Can someone be prosecuted for hacking into critical infrastructure systems in India?",
    "How does Indian law address online animal cruelty?",
    "Can individuals be held liable for sharing pirated academic materials online in India?",
    "What are the regulations for online auction websites in India?",
    "Can someone be prosecuted for manipulating online voting systems in India?",
    "How does Indian law address online harassment in online gaming communities?",
    "Are there specific regulations for online crowdfunding platforms in India?",
    "Can individuals be prosecuted for hacking into religious institutions' websites in India?",
    "What are the legal consequences of cyberbullying in the workplace under Indian law?",
    "Can someone be prosecuted for hacking into environmental organizations' databases in India?",
    "How does Indian law address online harassment targeting marginalized communities?",
    "Can individuals be held liable for hacking into emergency service systems' networks in India?",
    "What are the regulations for online streaming platforms regarding content moderation in India?",
    "Can someone be prosecuted for hacking into space research organizations' databases in India?",
    "How does Indian law address online harassment targeting indigenous communities?",
    "Can individuals be prosecuted for hacking into disaster relief organizations' systems in India?",
    "What are the legal consequences of cyberbullying targeting refugees in India?",
    "Can someone be held liable for hacking into international organizations' networks in India?",
    "How does Indian law address online harassment targeting immigrants?",
    "Can individuals be prosecuted for hacking into organizations supporting victims of violence in India?",
    "What are the legal implications of cyberbullying targeting individuals with chronic illnesses in India?",
    "Can someone be prosecuted for hacking into organizations providing aid to refugees in India?",
    "How does Indian law address online harassment targeting elders?",
    "Can individuals be held liable for hacking into organizations supporting survivors of abuse in India?",
    "What are the legal consequences of cyberbullying targeting people with mental health issues in India?",
    "Can someone be prosecuted for hacking into organizations providing mental health support in India?",
    "How does Indian law address online harassment targeting individuals with eating disorders?",
    "Can individuals be prosecuted for hacking into organizations providing support to victims of human trafficking in India?",
    "What are the legal consequences of cyberbullying targeting individuals with autism in India?",
    "Can someone be held liable for hacking into organizations providing support to victims of domestic violence in India?",
    "How does Indian law address online harassment targeting individuals with learning disabilities?",
    "Can individuals be prosecuted for hacking into organizations providing support to victims of sexual assault in India?",
    "What are the legal implications of cyberbullying targeting individuals with physical disabilities in India?",
    "Can someone be prosecuted for hacking into organizations providing support to victims of child abuse in India?",
  "What are the powers and duties of the police force under the Indian Constitution?",
    "How does the Indian Constitution regulate the functioning of the police force?",
    "What are the constitutional provisions regarding the organization of the police force in India?",
    "Can the police force in India operate independently of political influence as per the Constitution?",
    "What are the constitutional safeguards to ensure the independence of the police force?",
    "How does the Indian Constitution protect the fundamental rights of citizens in encounters with the police?",
    "Are there any limitations on the powers of the police force regarding arrest and detention under the Constitution?",
    "What constitutional provisions govern the investigation process carried out by the police?",
    "Can the police force in India use excessive force against citizens, according to the Constitution?",
    "What are the constitutional provisions regarding the accountability of the police force for human rights violations?",
    "How does the Indian Constitution address issues of police brutality and custodial violence?",
    "Can the police force be held liable for illegal actions or negligence as per the Constitution?",
    "What role does the judiciary play in ensuring accountability and oversight of the police force under the Constitution?",
    "Are there any constitutional provisions for the protection of whistleblowers within the police force?",
    "How does the Indian Constitution address issues of corruption within the police force?",
    "Can the police force be subjected to disciplinary action for misconduct under the Constitution?",
    "What constitutional provisions regulate the deployment of the armed forces within the country?",
    "Can the army be deployed for internal security purposes under the Indian Constitution?",
    "What are the constitutional safeguards to prevent the misuse of the armed forces for internal security?",
    "Can the army conduct operations against civilians within the country as per the Constitution?",
    "How does the Indian Constitution ensure civilian control over the armed forces?",
    "What constitutional provisions govern the use of force by the armed forces during internal security operations?",
    "Can the armed forces be held accountable for human rights violations during internal security operations according to the Constitution?",
    "Are there any limitations on the powers of the armed forces regarding the arrest and detention of civilians under the Constitution?",
    "What role does the judiciary play in overseeing the actions of the armed forces during internal security operations?",
    "Can civilians file legal complaints against the armed forces for misconduct or human rights violations under the Constitution?",
    "How does the Indian Constitution address issues of compensation for victims of human rights violations by the armed forces?",
    "Can the armed forces be prosecuted in civilian courts for offenses committed during internal security operations?",
    "What constitutional provisions regulate the use of emergency powers by the armed forces?",
    "Can the armed forces impose martial law in India under the Constitution?",
    "How does the Indian Constitution address issues of accountability and transparency in the deployment of the armed forces during emergencies?",
    "Can civilians challenge the imposition of emergency powers by the armed forces in court according to the Constitution?",
    "What are the constitutional provisions regarding the role of the President in deploying the armed forces during emergencies?",
    "Can the armed forces be deployed to assist the police during law enforcement operations under the Constitution?",
    "How does the Indian Constitution ensure coordination between the police and armed forces during joint operations?",
    "Can the armed forces be involved in counter-terrorism operations within the country under the Constitution?",
    "What constitutional provisions govern the use of intelligence agencies in coordination with the armed forces for internal security purposes?",
    "Can civilians be subjected to military courts during internal security operations according to the Constitution?",
    "How does the Indian Constitution ensure the protection of civilian rights during military operations within the country?",
    "Can the armed forces be deployed to quell civil unrest or protests under the Constitution?",
    "What constitutional provisions regulate the use of non-lethal weapons by the armed forces during crowd control operations?",
    "Can the armed forces use deadly force against civilians during protests according to the Constitution?",
    "How does the Indian Constitution ensure transparency and accountability in the use of force by the armed forces during protests?",
    "Can civilians challenge the actions of the armed forces during protests in court under the Constitution?",
    "What are the constitutional provisions regarding the use of surveillance and intelligence-gathering by the armed forces for internal security purposes?",
    "Can the armed forces conduct preemptive strikes against perceived threats to national security within the country under the Constitution?",
    "How does the Indian Constitution ensure the protection of individual liberties during military operations within the country?",
    "Can the armed forces be deployed to enforce curfews or lockdowns during emergencies according to the Constitution?",
    "What constitutional provisions regulate the use of checkpoints and roadblocks by the armed forces for internal security purposes?",
    "Can civilians be subjected to interrogation or detention by the armed forces during internal security operations under the Constitution?",
    "How does the Indian Constitution ensure the protection of minority rights during military operations within the country?",
    "Can the armed forces be deployed to assist in disaster relief operations under the Constitution?",
    "What constitutional provisions govern the use of military resources for civilian purposes during emergencies?",
    "Can civilians be conscripted into the armed forces during emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of property rights during military operations within the country?",
    "Can the armed forces be deployed to protect critical infrastructure during emergencies under the Constitution?",
    "What constitutional provisions regulate the use of lethal force by the armed forces to protect infrastructure and essential services?",
    "Can civilians be displaced or evacuated by the armed forces during emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of vulnerable populations during military operations within the country?",
    "Can the armed forces be deployed to enforce quarantine or isolation measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to enforce public health regulations?",
    "Can civilians be subjected to compulsory vaccination by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of bodily integrity and autonomy during vaccination campaigns by the armed forces?",
    "Can the armed forces be deployed to enforce quarantine or isolation measures for infectious diseases under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to maintain quarantine or isolation facilities?",
    "Can civilians be detained or isolated by the armed forces for refusing to comply with quarantine orders according to the Constitution?",
    "How does the Indian Constitution ensure the protection of due process rights during quarantine or isolation measures by the armed forces?",
    "Can the armed forces be deployed to enforce travel restrictions during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to restrict movement during emergencies?",
    "Can civilians be subjected to travel bans or restrictions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of freedom of movement during travel restrictions imposed by the armed forces?",
    "Can the armed forces be deployed to enforce lockdowns or curfews during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to restrict movement during lockdowns?",
    "Can civilians be subjected to house arrest or confinement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of liberty and security during lockdowns imposed by the armed forces?",
    "Can the armed forces be deployed to enforce hygiene and sanitation measures during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with hygiene regulations?",
    "Can civilians be subjected to hygiene inspections or interventions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of dignity and privacy during hygiene interventions by the armed forces?",
    "Can the armed forces be deployed to enforce social distancing measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with social distancing regulations?",
    "Can civilians be subjected to physical distancing or isolation measures by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of social and familial ties during social distancing measures imposed by the armed forces?",
    "Can the armed forces be deployed to enforce mask mandates during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with mask-wearing regulations?",
    "Can civilians be subjected to mask requirements or enforcement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of individual expression and identity during mask mandates imposed by the armed forces?",
    "Can the armed forces be deployed to enforce testing and screening measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with testing and screening protocols?",
    "Can civilians be subjected to mandatory testing or screening by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of bodily integrity and autonomy during testing and screening interventions by the armed forces?",
    "Can the armed forces be deployed to enforce quarantine or isolation measures for infectious diseases under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to maintain quarantine or isolation facilities?",
    "Can civilians be detained or isolated by the armed forces for refusing to comply with quarantine orders according to the Constitution?",
    "How does the Indian Constitution ensure the protection of due process rights during quarantine or isolation measures by the armed forces?",
    "Can the armed forces be deployed to enforce travel restrictions during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to restrict movement during emergencies?",
    "Can civilians be subjected to travel bans or restrictions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of freedom of movement during travel restrictions imposed by the armed forces?",
    "Can the armed forces be deployed to enforce lockdowns or curfews during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to restrict movement during lockdowns?",
    "Can civilians be subjected to house arrest or confinement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of liberty and security during lockdowns imposed by the armed forces?",
    "Can the armed forces be deployed to enforce hygiene and sanitation measures during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with hygiene regulations?",
    "Can civilians be subjected to hygiene inspections or interventions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of dignity and privacy during hygiene interventions by the armed forces?",
    "Can the armed forces be deployed to enforce social distancing measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with social distancing regulations?",
    "Can civilians be subjected to physical distancing or isolation measures by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of social and familial ties during social distancing measures imposed by the armed forces?",
    "Can the armed forces be deployed to enforce mask mandates during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with mask-wearing regulations?",
    "Can civilians be subjected to mask requirements or enforcement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of individual expression and identity during mask mandates imposed by the armed forces?",
    "Can the armed forces be deployed to enforce testing and screening measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with testing and screening protocols?",
    "Can civilians be subjected to mandatory testing or screening by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of bodily integrity and autonomy during testing and screening interventions by the armed forces?",
    "Can the armed forces be deployed to enforce quarantine or isolation measures for infectious diseases under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to maintain quarantine or isolation facilities?",
    "Can civilians be detained or isolated by the armed forces for refusing to comply with quarantine orders according to the Constitution?",
    "How does the Indian Constitution ensure the protection of due process rights during quarantine or isolation measures by the armed forces?",
    "Can the armed forces be deployed to enforce travel restrictions during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to restrict movement during emergencies?",
    "Can civilians be subjected to travel bans or restrictions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of freedom of movement during travel restrictions imposed by the armed forces?",
    "Can the armed forces be deployed to enforce lockdowns or curfews during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to restrict movement during lockdowns?",
    "Can civilians be subjected to house arrest or confinement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of liberty and security during lockdowns imposed by the armed forces?",
    "Can the armed forces be deployed to enforce hygiene and sanitation measures during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with hygiene regulations?",
    "Can civilians be subjected to hygiene inspections or interventions by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of dignity and privacy during hygiene interventions by the armed forces?",
    "Can the armed forces be deployed to enforce social distancing measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with social distancing regulations?",
    "Can civilians be subjected to physical distancing or isolation measures by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of social and familial ties during social distancing measures imposed by the armed forces?",
    "Can the armed forces be deployed to enforce mask mandates during public health emergencies under the Constitution?",
    "What constitutional provisions regulate the use of force by the armed forces to ensure compliance with mask-wearing regulations?",
    "Can civilians be subjected to mask requirements or enforcement by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of individual expression and identity during mask mandates imposed by the armed forces?",
    "Can the armed forces be deployed to enforce testing and screening measures during public health emergencies under the Constitution?",
    "What constitutional provisions govern the use of force by the armed forces to ensure compliance with testing and screening protocols?",
    "Can civilians be subjected to mandatory testing or screening by the armed forces during public health emergencies according to the Constitution?",
    "How does the Indian Constitution ensure the protection of bodily integrity and autonomy during testing and screening interventions by the armed forces?"
]

