questions = [
    "What is the definition of 'criminal law' according to the Indian legal system?",
    "Can you explain the concept of 'mens rea' in criminal law?",
    "What are the different types of criminal offenses recognized in Indian law?",
    "How does Indian law define 'attempt to commit a crime'?",
    "What are the essential elements of a crime under Indian criminal law?",
    "Can you explain the principle of 'actus reus' in criminal law?",
    "What is the difference between 'murder' and 'culpable homicide' under Indian law?",
    "When does 'self-defense' apply in Indian criminal law?",
    "What constitutes 'abetment' of a crime according to Indian law?",
    "Can you explain the concept of 'criminal conspiracy' under Indian law?",
    "What are the different punishments prescribed for various criminal offenses in India?",
    "How does Indian law define 'theft'?",
    "Can you explain the legal principles regarding 'criminal trespass' in India?",
    "What is the punishment for 'cheating' under the Indian Penal Code?",
    "Can you explain the provisions related to 'forgery' in Indian criminal law?",
    "What constitutes 'rioting' under Indian law?",
    "What are the legal provisions regarding 'cybercrime' in India?",
    "Can you explain the concept of 'white-collar crime' under Indian law?",
    "What is the punishment for 'criminal breach of trust' in India?",
    "How does Indian law define 'kidnapping' and 'abduction'?",
    "Can you explain the legal provisions related to 'sexual offenses' in India?",
    "What constitutes 'criminal intimidation' under the Indian Penal Code?",
    "How does Indian law address 'child labor' as a criminal offense?",
    "What are the legal provisions regarding 'narcotic drugs and psychotropic substances' in India?",
    "Can you explain the concept of 'criminal negligence' under Indian law?",
    "What is the punishment for 'attempt to suicide' under Indian law?",
    "How does Indian law define 'abetment of suicide'?",
    "Can you explain the legal provisions regarding 'corruption' in India?",
    "What constitutes 'criminal defamation' under Indian law?",
    "What are the legal provisions regarding 'economic offenses' in India?",
    "How does Indian law address 'environmental crimes'?",
    "Can you explain the provisions related to 'human trafficking' in Indian law?",
    "What are the legal provisions regarding 'offenses against the state' in India?",
    "How does Indian law address 'cyberbullying'?",
    "What constitutes 'stalking' as a criminal offense in India?",
    "What are the legal provisions regarding 'counterfeiting' in India?",
    "Can you explain the punishment for 'attempt to commit suicide' under Indian law?",
    "How does Indian law address 'cyberstalking'?",
    "What constitutes 'criminal breach of contract' under Indian law?",
    "Can you explain the legal provisions regarding 'embezzlement' in India?",
    "What is the punishment for 'extortion' under the Indian Penal Code?",
    "How does Indian law address 'fraudulent misrepresentation'?",
    "What constitutes 'criminal harassment' under Indian law?",
    "Can you explain the legal provisions regarding 'money laundering' in India?",
    "What is the punishment for 'perjury' under Indian law?",
    "How does Indian law address 'sexual harassment' in the workplace?",
    "What constitutes 'criminal trespass to land' under the Indian Penal Code?",
    "Can you explain the legal provisions regarding 'forgery for the purpose of cheating' in India?",
    "What is the punishment for 'impersonation' under Indian law?",
    "How does Indian law address 'cyber terrorism'?",
    "What constitutes 'criminal misappropriation of property' under Indian law?",
    "Can you explain the legal provisions regarding 'bribery' in India?",
    "What is the punishment for 'embezzlement of property entrusted' under Indian law?",
    "How does Indian law address 'domestic violence' as a criminal offense?",
    "What constitutes 'criminal breach of trust by a public servant' under Indian law?",
    "Can you explain the legal provisions regarding 'insider trading' in India?",
    "What is the punishment for 'identity theft' under Indian law?",
    "How does Indian law address 'juvenile delinquency'?",
    "What constitutes 'criminal intimidation by an anonymous communication' under Indian law?",
    "Can you explain the legal provisions regarding 'forgery of valuable security' in India?",
    "What is the punishment for 'negligent conduct with respect to poisonous substances' under Indian law?",
    "How does Indian law address 'outraging the modesty of a woman'?",
    "What constitutes 'criminal intimidation by posing as a person of authority' under Indian law?",
    "Can you explain the legal provisions regarding 'possession of counterfeit currency notes' in India?",
    "What is the punishment for 'public nuisance' under Indian law?",
    "How does Indian law address 'rape' and 'sexual assault'?",
    "What constitutes 'criminal intimidation for extortion' under Indian law?",
    "Can you explain the legal provisions regarding 'receiving stolen property' in India?",
    "What is the punishment for 'sale of adulterated drugs' under Indian law?",
    "How does Indian law address 'sedition' as a criminal offense?",
    "What constitutes 'criminal breach of trust by a banker' under Indian law?",
    "Can you explain the legal provisions regarding 'trafficking of persons for forced labor' in India?",
    "What is the punishment for 'unlawful assembly' under Indian law?",
    "How does Indian law address 'voyeurism' as a criminal offense?",
    "What constitutes 'criminal liability for omission to act' under Indian law?",
    "Can you explain the legal provisions regarding 'abetment of desertion of soldier' in India?",
    "What is the punishment for 'adultery' under Indian law?",
    "How does Indian law address 'causing miscarriage without woman's consent'?",
    "What constitutes 'criminal liab
